/**
 * Signals Page - Vision-IoS Dashboard
 * Trading signals and alerts
 *
 * Data Lineage:
 * - fhq_finn.signal_events
 */

import { Card } from '@/components/ui/Card';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { SkeletonCard } from '@/components/ui/Skeleton';
import { getSignals } from '@/lib/data';
import { formatRelativeTime, cn } from '@/lib/utils';
import { Suspense } from 'react';

export const dynamic = 'force-dynamic';

async function SignalsFeed() {
  const signals = await getSignals(20, false);

  const signalTypeColors: Record<string, string> = {
    buy: 'text-trust-green bg-trust-green/10 border-trust-green/20',
    sell: 'text-trust-red bg-trust-red/10 border-trust-red/20',
    hold: 'text-trust-yellow bg-trust-yellow/10 border-trust-yellow/20',
    alert: 'text-trust-blue bg-trust-blue/10 border-trust-blue/20',
  };

  return (
    <Card
      title="Signal Events"
      subtitle="Trading signals from FINN and LARS"
      lineage={['fhq_finn.signal_events']}
    >
      {signals.length === 0 ? (
        <div className="text-center py-8">
          <p className="text-gray-400">No signals available</p>
          <p className="text-xs text-gray-500 mt-2">
            Signals will appear here when generated by FINN or LARS agents
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {signals.map((signal) => (
            <div
              key={signal.signalId}
              className={cn(
                'border rounded-lg p-4 transition-all',
                signal.isActive
                  ? 'border-fjord-600 bg-fjord-800/50'
                  : 'border-fjord-700/50 bg-fjord-800/25 opacity-60'
              )}
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-center gap-3">
                  <span className={cn(
                    'px-3 py-1 rounded-full text-sm font-medium uppercase border',
                    signalTypeColors[signal.signalType] || signalTypeColors.alert
                  )}>
                    {signal.signalType}
                  </span>
                  <span className="font-mono text-lg text-white">{signal.ticker}</span>
                </div>
                <div className="text-right">
                  <div className="flex items-center gap-2">
                    <span className="text-sm text-gray-400">Strength:</span>
                    <span className={cn(
                      'font-semibold',
                      signal.strength > 0.7 ? 'text-trust-green' :
                      signal.strength > 0.4 ? 'text-trust-yellow' : 'text-trust-red'
                    )}>
                      {(signal.strength * 100).toFixed(0)}%
                    </span>
                  </div>
                  <div className="flex items-center gap-2 mt-1">
                    <span className="text-sm text-gray-400">Confidence:</span>
                    <span className="text-white font-medium">
                      {(signal.confidence * 100).toFixed(0)}%
                    </span>
                  </div>
                </div>
              </div>

              {signal.rationale && (
                <p className="text-gray-300 mt-3">{signal.rationale}</p>
              )}

              <div className="flex items-center justify-between mt-3 pt-3 border-t border-fjord-700">
                <div className="flex items-center gap-2">
                  <StatusBadge status={signal.sourceAgent} size="sm" variant="agent" />
                  <span className="text-xs text-gray-500">
                    {formatRelativeTime(signal.generatedAt || new Date())}
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  {signal.isActive ? (
                    <StatusBadge status="ACTIVE" size="sm" />
                  ) : (
                    <StatusBadge status="EXPIRED" size="sm" />
                  )}
                  {signal.expiresAt && (
                    <span className="text-xs text-gray-500">
                      Expires: {formatRelativeTime(signal.expiresAt)}
                    </span>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </Card>
  );
}

async function SignalStats() {
  const signals = await getSignals(100, false);

  const stats = {
    total: signals.length,
    active: signals.filter(s => s.isActive).length,
    buy: signals.filter(s => s.signalType === 'buy').length,
    sell: signals.filter(s => s.signalType === 'sell').length,
    hold: signals.filter(s => s.signalType === 'hold').length,
    alert: signals.filter(s => s.signalType === 'alert').length,
    avgStrength: signals.length > 0
      ? signals.reduce((acc, s) => acc + s.strength, 0) / signals.length
      : 0,
    avgConfidence: signals.length > 0
      ? signals.reduce((acc, s) => acc + s.confidence, 0) / signals.length
      : 0,
    byAgent: signals.reduce((acc, s) => {
      acc[s.sourceAgent] = (acc[s.sourceAgent] || 0) + 1;
      return acc;
    }, {} as Record<string, number>),
  };

  return (
    <Card
      title="Signal Statistics"
      subtitle="Aggregate signal metrics"
      lineage={['fhq_finn.signal_events']}
    >
      <div className="space-y-6">
        {/* Summary */}
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-fjord-700/30 rounded-lg p-3">
            <span className="text-xs text-gray-400">Total Signals</span>
            <p className="text-2xl font-bold text-white">{stats.total}</p>
          </div>
          <div className="bg-fjord-700/30 rounded-lg p-3">
            <span className="text-xs text-gray-400">Active</span>
            <p className="text-2xl font-bold text-trust-green">{stats.active}</p>
          </div>
        </div>

        {/* By Type */}
        <div>
          <h4 className="text-sm text-gray-400 mb-3">By Type</h4>
          <div className="space-y-2">
            {[
              { type: 'buy', count: stats.buy, color: 'bg-trust-green' },
              { type: 'sell', count: stats.sell, color: 'bg-trust-red' },
              { type: 'hold', count: stats.hold, color: 'bg-trust-yellow' },
              { type: 'alert', count: stats.alert, color: 'bg-trust-blue' },
            ].map(({ type, count, color }) => (
              <div key={type} className="flex items-center gap-3">
                <span className="text-xs text-gray-400 w-12 uppercase">{type}</span>
                <div className="flex-1 h-2 bg-fjord-700 rounded-full overflow-hidden">
                  <div
                    className={cn('h-full rounded-full', color)}
                    style={{ width: stats.total > 0 ? `${(count / stats.total) * 100}%` : '0%' }}
                  />
                </div>
                <span className="text-sm text-white w-8 text-right">{count}</span>
              </div>
            ))}
          </div>
        </div>

        {/* By Agent */}
        <div>
          <h4 className="text-sm text-gray-400 mb-3">By Agent</h4>
          <div className="flex flex-wrap gap-2">
            {Object.entries(stats.byAgent).map(([agent, count]) => (
              <div key={agent} className="flex items-center gap-2 bg-fjord-700/30 rounded-lg px-3 py-2">
                <StatusBadge status={agent} size="sm" variant="agent" />
                <span className="text-white font-medium">{count}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Averages */}
        <div className="grid grid-cols-2 gap-4">
          <div>
            <span className="text-xs text-gray-400">Avg Strength</span>
            <p className="text-lg font-semibold text-white">
              {(stats.avgStrength * 100).toFixed(1)}%
            </p>
          </div>
          <div>
            <span className="text-xs text-gray-400">Avg Confidence</span>
            <p className="text-lg font-semibold text-white">
              {(stats.avgConfidence * 100).toFixed(1)}%
            </p>
          </div>
        </div>
      </div>
    </Card>
  );
}

export default function SignalsPage() {
  return (
    <div className="space-y-6 animate-fade-in">
      {/* Page Header */}
      <div>
        <h1 className="text-2xl font-bold text-white">Signals</h1>
        <p className="text-gray-400 mt-1">
          Trading signals and alerts generated by FINN and LARS agents
        </p>
      </div>

      {/* Main Content */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2">
          <Suspense fallback={<SkeletonCard />}>
            <SignalsFeed />
          </Suspense>
        </div>
        <Suspense fallback={<SkeletonCard />}>
          <SignalStats />
        </Suspense>
      </div>
    </div>
  );
}
