-- ============================================================================
-- Migration 176: CEO-DIR-2026-015 Driver Attribution Truth Protocol (DDATP)
-- ============================================================================
-- Authority: CEO Directive CEO-DIR-2026-015
-- Classification: Governance - Epistemic Integrity
-- Scope: SHADOW + PRODUCTION SAFE (metadata only, no trading impact)
-- Generated: 2026-01-07
-- Generated By: STIG
--
-- PURPOSE:
-- Replace single dominant_driver with 4-part structure to prevent
-- "SENTIMENT without sentiment" mislabeling and enable audit-grade
-- attribution provenance.
--
-- CHANGES:
-- 1. Add driver_claim, driver_basis, input_coverage, fallback_reason to:
--    - fhq_perception.sovereign_regime_state_v4
--    - fhq_research.nightly_insights
-- 2. Add technical_feature_set per CEO Correction A
-- 3. Create VEGA integrity trigger per CEO Correction B
-- 4. Legacy fields remain untouched for backward compatibility
-- ============================================================================

BEGIN;

-- ============================================================================
-- STEP 1: Add new columns to sovereign_regime_state_v4
-- ============================================================================

ALTER TABLE fhq_perception.sovereign_regime_state_v4
ADD COLUMN IF NOT EXISTS driver_claim VARCHAR(20) CHECK (driver_claim IN (
    'LIQUIDITY',
    'CREDIT',
    'VOLATILITY',
    'TECHNICAL',
    'PRICE_ACTION',
    'SENTIMENT',
    'UNKNOWN'
)),
ADD COLUMN IF NOT EXISTS driver_basis VARCHAR(20) CHECK (driver_basis IN (
    'OBSERVED_DATA',
    'INFERRED_FROM_PRICE',
    'FALLBACK_UNKNOWN'
)),
ADD COLUMN IF NOT EXISTS input_coverage JSONB DEFAULT '{
    "macro_available": false,
    "macro_used": false,
    "macro_staleness_hours": null,
    "sentiment_available": false,
    "sentiment_used": false,
    "sentiment_staleness_hours": null,
    "technical_available": false,
    "technical_used": false,
    "onchain_available": false,
    "onchain_used": false
}'::jsonb,
ADD COLUMN IF NOT EXISTS fallback_reason TEXT,
ADD COLUMN IF NOT EXISTS technical_feature_set VARCHAR(20) CHECK (technical_feature_set IN (
    'INDICATORS_ONLY',
    'RETURNS_VOL_ONLY',
    'MIXED_FEATURES',
    'ONCHAIN_HYBRID',
    'UNKNOWN'
)),
ADD COLUMN IF NOT EXISTS ddatp_version VARCHAR(10) DEFAULT 'v1.0';

-- ============================================================================
-- STEP 2: Add new columns to nightly_insights
-- ============================================================================

ALTER TABLE fhq_research.nightly_insights
ADD COLUMN IF NOT EXISTS driver_claim VARCHAR(20) CHECK (driver_claim IN (
    'LIQUIDITY',
    'CREDIT',
    'VOLATILITY',
    'TECHNICAL',
    'PRICE_ACTION',
    'SENTIMENT',
    'UNKNOWN'
)),
ADD COLUMN IF NOT EXISTS driver_basis VARCHAR(20) CHECK (driver_basis IN (
    'OBSERVED_DATA',
    'INFERRED_FROM_PRICE',
    'FALLBACK_UNKNOWN'
)),
ADD COLUMN IF NOT EXISTS input_coverage JSONB DEFAULT '{
    "macro_available": false,
    "macro_used": false,
    "macro_staleness_hours": null,
    "sentiment_available": false,
    "sentiment_used": false,
    "sentiment_staleness_hours": null,
    "technical_available": false,
    "technical_used": false,
    "onchain_available": false,
    "onchain_used": false
}'::jsonb,
ADD COLUMN IF NOT EXISTS fallback_reason TEXT,
ADD COLUMN IF NOT EXISTS technical_feature_set VARCHAR(20) CHECK (technical_feature_set IN (
    'INDICATORS_ONLY',
    'RETURNS_VOL_ONLY',
    'MIXED_FEATURES',
    'ONCHAIN_HYBRID',
    'UNKNOWN'
)),
ADD COLUMN IF NOT EXISTS ddatp_version VARCHAR(10) DEFAULT 'v1.0';

-- ============================================================================
-- STEP 3: Create VEGA integrity trigger for DDATP enforcement
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.enforce_ddatp_integrity()
RETURNS TRIGGER AS $$
BEGIN
    -- ========================================================================
    -- Rule 1: SENTIMENT claim requires sentiment_used = true
    -- CEO Correction B: "feed used" not just "feed exists"
    -- ========================================================================
    IF NEW.driver_claim = 'SENTIMENT' THEN
        IF NOT COALESCE((NEW.input_coverage->>'sentiment_used')::boolean, false) THEN
            RAISE EXCEPTION 'DDATP VIOLATION [Rule 1]: SENTIMENT claim requires sentiment_used=true. Got input_coverage=%',
                NEW.input_coverage;
        END IF;
    END IF;

    -- ========================================================================
    -- Rule 2: OBSERVED_DATA basis requires at least one external feed USED
    -- CEO Correction B: Check *_used not just *_available
    -- ========================================================================
    IF NEW.driver_basis = 'OBSERVED_DATA' THEN
        IF NOT (
            COALESCE((NEW.input_coverage->>'macro_used')::boolean, false) OR
            COALESCE((NEW.input_coverage->>'sentiment_used')::boolean, false) OR
            COALESCE((NEW.input_coverage->>'onchain_used')::boolean, false)
        ) THEN
            RAISE EXCEPTION 'DDATP VIOLATION [Rule 2]: OBSERVED_DATA basis requires at least one *_used=true. Got input_coverage=%',
                NEW.input_coverage;
        END IF;
    END IF;

    -- ========================================================================
    -- Rule 3: Fallback reason required when basis != OBSERVED_DATA
    -- ========================================================================
    IF NEW.driver_basis IS NOT NULL AND NEW.driver_basis != 'OBSERVED_DATA' THEN
        IF NEW.fallback_reason IS NULL OR NEW.fallback_reason = '' THEN
            RAISE EXCEPTION 'DDATP VIOLATION [Rule 3]: fallback_reason required when driver_basis=%. Got NULL',
                NEW.driver_basis;
        END IF;
    END IF;

    -- ========================================================================
    -- Rule 4: TECHNICAL claim must specify technical_feature_set
    -- CEO Correction A: Disambiguate TECHNICAL vs PRICE_ACTION
    -- ========================================================================
    IF NEW.driver_claim = 'TECHNICAL' THEN
        IF NEW.technical_feature_set IS NULL THEN
            RAISE EXCEPTION 'DDATP VIOLATION [Rule 4]: TECHNICAL claim requires technical_feature_set. Got NULL';
        END IF;
    END IF;

    -- ========================================================================
    -- Rule 5: PRICE_ACTION only allowed with RETURNS_VOL_ONLY or absent indicators
    -- CEO Correction A: Enforce semantic consistency
    -- ========================================================================
    IF NEW.driver_claim = 'PRICE_ACTION' THEN
        IF NEW.technical_feature_set IS NOT NULL
           AND NEW.technical_feature_set NOT IN ('RETURNS_VOL_ONLY', 'UNKNOWN') THEN
            RAISE EXCEPTION 'DDATP VIOLATION [Rule 5]: PRICE_ACTION incompatible with technical_feature_set=%. Must be RETURNS_VOL_ONLY or UNKNOWN',
                NEW.technical_feature_set;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to sovereign_regime_state_v4
DROP TRIGGER IF EXISTS trg_ddatp_sovereign_regime ON fhq_perception.sovereign_regime_state_v4;
CREATE TRIGGER trg_ddatp_sovereign_regime
    BEFORE INSERT OR UPDATE ON fhq_perception.sovereign_regime_state_v4
    FOR EACH ROW
    WHEN (NEW.driver_claim IS NOT NULL)  -- Only enforce when DDATP fields are populated
    EXECUTE FUNCTION fhq_governance.enforce_ddatp_integrity();

-- Apply trigger to nightly_insights
DROP TRIGGER IF EXISTS trg_ddatp_nightly_insights ON fhq_research.nightly_insights;
CREATE TRIGGER trg_ddatp_nightly_insights
    BEFORE INSERT OR UPDATE ON fhq_research.nightly_insights
    FOR EACH ROW
    WHEN (NEW.driver_claim IS NOT NULL)  -- Only enforce when DDATP fields are populated
    EXECUTE FUNCTION fhq_governance.enforce_ddatp_integrity();

-- ============================================================================
-- STEP 4: Create index for driver attribution queries
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_sovereign_regime_ddatp
ON fhq_perception.sovereign_regime_state_v4 (driver_claim, driver_basis)
WHERE driver_claim IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_nightly_insights_ddatp
ON fhq_research.nightly_insights (driver_claim, driver_basis)
WHERE driver_claim IS NOT NULL;

-- ============================================================================
-- STEP 5: Log migration in governance audit
-- ============================================================================

INSERT INTO fhq_governance.governance_actions_log (
    action_id,
    action_type,
    action_target,
    action_target_type,
    initiated_by,
    initiated_at,
    decision,
    decision_rationale,
    metadata,
    agent_id,
    timestamp
) VALUES (
    gen_random_uuid(),
    'SCHEMA_MIGRATION',
    'CEO-DIR-2026-015',
    'DIRECTIVE',
    'STIG',
    NOW(),
    'EXECUTED',
    'Driver Attribution Truth Protocol (DDATP) - Migration 176 executed successfully',
    jsonb_build_object(
        'migration_id', 176,
        'directive', 'CEO-DIR-2026-015',
        'title', 'Driver Attribution Truth Protocol (DDATP)',
        'tables_modified', ARRAY['fhq_perception.sovereign_regime_state_v4', 'fhq_research.nightly_insights'],
        'columns_added', ARRAY['driver_claim', 'driver_basis', 'input_coverage', 'fallback_reason', 'technical_feature_set', 'ddatp_version'],
        'trigger_created', 'fhq_governance.enforce_ddatp_integrity()',
        'ceo_corrections_implemented', ARRAY['A: technical_feature_set disambiguation', 'B: *_used enforcement'],
        'lineage_hash', encode(sha256(('CEO-DIR-2026-015-MIGRATION-176-' || NOW()::text)::bytea), 'hex')
    ),
    'STIG',
    NOW()
);

COMMIT;

-- ============================================================================
-- VERIFICATION QUERY (run after migration)
-- ============================================================================
-- SELECT
--     column_name, data_type, column_default
-- FROM information_schema.columns
-- WHERE table_schema = 'fhq_perception'
--   AND table_name = 'sovereign_regime_state_v4'
--   AND column_name IN ('driver_claim', 'driver_basis', 'input_coverage', 'fallback_reason', 'technical_feature_set');
