-- ============================================================================
-- Migration 270: FSS (Forecast Skill Score) Computation
-- CEO-DIR-2026-101 Phase A2 - GAP-COMP-001 Remediation
-- ============================================================================
-- Purpose: Implement compute_fss() function and temporal integrity enforcement
--
-- Constitutional Alignment: ADR-018, ADR-019, ADR-020
-- VEGA Gate: G3 Required
-- Generated By: STIG (EC-003_2026_PRODUCTION)
-- Generated At: 2026-01-19
--
-- FSS Formula: FSS = 1 - (Brier / Brier_ref)
-- Where Brier_ref can be:
--   - NAIVE: 0.25 (50/50 coin flip equivalent)
--   - ROLLING_30D: 30-day rolling mean Brier for asset
--   - REGIME_SPECIFIC: Historical Brier for same regime
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECTION 1: Temporal Contamination Prevention
-- ============================================================================
-- Per CEO-DIR-2026-101: "forecast_time >= outcome_time" is CONTAMINATION

CREATE OR REPLACE FUNCTION fhq_governance.prevent_temporal_contamination()
RETURNS TRIGGER AS $$
BEGIN
    -- Check temporal integrity: forecast must be BEFORE outcome
    IF NEW.forecast_timestamp IS NOT NULL AND NEW.outcome_timestamp IS NOT NULL THEN
        IF NEW.forecast_timestamp >= NEW.outcome_timestamp THEN
            RAISE EXCEPTION 'TEMPORAL_CONTAMINATION: forecast_timestamp (%) must be < outcome_timestamp (%). This violates ex-ante verification requirement.',
                NEW.forecast_timestamp, NEW.outcome_timestamp;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to brier_score_ledger
DROP TRIGGER IF EXISTS trg_temporal_integrity ON fhq_governance.brier_score_ledger;

CREATE TRIGGER trg_temporal_integrity
BEFORE INSERT OR UPDATE ON fhq_governance.brier_score_ledger
FOR EACH ROW EXECUTE FUNCTION fhq_governance.prevent_temporal_contamination();

COMMENT ON FUNCTION fhq_governance.prevent_temporal_contamination() IS
'CEO-DIR-2026-101: Prevents temporal contamination by blocking rows where forecast_time >= outcome_time';


-- ============================================================================
-- SECTION 2: FSS Computation Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_research.compute_fss(
    p_asset_id TEXT DEFAULT NULL,
    p_start_date DATE DEFAULT NULL,
    p_end_date DATE DEFAULT NULL,
    p_baseline_method TEXT DEFAULT 'NAIVE',
    p_regime TEXT DEFAULT NULL
)
RETURNS TABLE (
    asset_id TEXT,
    brier_actual NUMERIC,
    brier_ref NUMERIC,
    fss_value NUMERIC,
    sample_size INTEGER,
    baseline_method TEXT,
    computed_for_period DATERANGE,
    evidence_hash TEXT
) AS $$
DECLARE
    v_default_start DATE := COALESCE(p_start_date, CURRENT_DATE - INTERVAL '30 days');
    v_default_end DATE := COALESCE(p_end_date, CURRENT_DATE);
BEGIN
    RETURN QUERY
    WITH asset_brier AS (
        -- Compute actual Brier for each asset
        SELECT
            bsl.asset_id,
            AVG(bsl.squared_error) AS avg_brier,
            COUNT(*) AS sample_count,
            bsl.regime
        FROM fhq_governance.brier_score_ledger bsl
        WHERE (p_asset_id IS NULL OR bsl.asset_id = p_asset_id)
          AND bsl.forecast_timestamp::DATE BETWEEN v_default_start AND v_default_end
          AND (p_regime IS NULL OR bsl.regime = p_regime)
          AND bsl.squared_error IS NOT NULL
        GROUP BY bsl.asset_id, bsl.regime
    ),
    baseline_calc AS (
        -- Compute reference baseline based on method
        SELECT
            ab.asset_id,
            ab.avg_brier,
            ab.sample_count,
            ab.regime,
            CASE p_baseline_method
                WHEN 'NAIVE' THEN 0.25  -- 50/50 coin flip
                WHEN 'ROLLING_30D' THEN (
                    SELECT COALESCE(AVG(bsl2.squared_error), 0.25)
                    FROM fhq_governance.brier_score_ledger bsl2
                    WHERE bsl2.asset_id = ab.asset_id
                      AND bsl2.forecast_timestamp::DATE BETWEEN v_default_start - INTERVAL '30 days' AND v_default_start
                )
                WHEN 'REGIME_SPECIFIC' THEN (
                    SELECT COALESCE(AVG(bsl3.squared_error), 0.25)
                    FROM fhq_governance.brier_score_ledger bsl3
                    WHERE bsl3.regime = ab.regime
                      AND bsl3.forecast_timestamp::DATE < v_default_start
                )
                ELSE 0.25  -- Default to naive
            END AS reference_baseline
        FROM asset_brier ab
    )
    SELECT
        bc.asset_id,
        bc.avg_brier::NUMERIC,
        bc.reference_baseline::NUMERIC,
        CASE
            WHEN bc.reference_baseline > 0 THEN
                (1 - (bc.avg_brier / bc.reference_baseline))::NUMERIC
            ELSE NULL
        END AS fss_value,
        bc.sample_count::INTEGER,
        p_baseline_method,
        daterange(v_default_start, v_default_end, '[]')::DATERANGE,
        ('sha256:' || encode(sha256(
            (bc.asset_id || bc.avg_brier::TEXT || bc.reference_baseline::TEXT || v_default_start::TEXT || v_default_end::TEXT)::bytea
        ), 'hex'))::TEXT
    FROM baseline_calc bc
    WHERE bc.sample_count >= 5  -- Minimum sample size for statistical validity
    ORDER BY bc.asset_id;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fhq_research.compute_fss(TEXT, DATE, DATE, TEXT, TEXT) IS
'CEO-DIR-2026-101: Computes Forecast Skill Score (FSS) = 1 - (Brier/Brier_ref).
Baseline methods: NAIVE (0.25), ROLLING_30D, REGIME_SPECIFIC.
Returns evidence_hash for court-proof verification.';


-- ============================================================================
-- SECTION 3: FSS Backfill Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_research.backfill_fss(
    p_baseline_method TEXT DEFAULT 'NAIVE'
)
RETURNS INTEGER AS $$
DECLARE
    v_updated INTEGER := 0;
    v_fss_record RECORD;
BEGIN
    -- Update forecast_skill_metrics with computed FSS values
    FOR v_fss_record IN
        SELECT * FROM fhq_research.compute_fss(
            p_asset_id := NULL,
            p_start_date := CURRENT_DATE - INTERVAL '90 days',
            p_end_date := CURRENT_DATE,
            p_baseline_method := p_baseline_method
        )
    LOOP
        UPDATE fhq_research.forecast_skill_metrics
        SET brier_skill_score = v_fss_record.fss_value
        WHERE asset_id = v_fss_record.asset_id
          AND brier_skill_score IS NULL;

        IF FOUND THEN
            v_updated := v_updated + 1;
        END IF;
    END LOOP;

    RETURN v_updated;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_research.backfill_fss(TEXT) IS
'CEO-DIR-2026-101: Backfills NULL brier_skill_score values in forecast_skill_metrics';


-- ============================================================================
-- SECTION 4: System-Level FSS View
-- ============================================================================

CREATE OR REPLACE VIEW fhq_research.v_system_fss AS
SELECT
    asset_id,
    brier_actual,
    brier_ref,
    fss_value,
    sample_size,
    baseline_method,
    computed_for_period,
    evidence_hash,
    CURRENT_TIMESTAMP AS computed_at
FROM fhq_research.compute_fss(
    p_baseline_method := 'NAIVE'
)
WHERE fss_value IS NOT NULL;

COMMENT ON VIEW fhq_research.v_system_fss IS
'CEO-DIR-2026-101: System-level FSS view using NAIVE baseline (0.25)';


-- ============================================================================
-- SECTION 5: FSS Audit Log
-- ============================================================================

CREATE TABLE IF NOT EXISTS fhq_research.fss_computation_log (
    log_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    computation_timestamp TIMESTAMPTZ DEFAULT NOW(),
    asset_id TEXT,
    brier_actual NUMERIC,
    brier_ref NUMERIC,
    fss_value NUMERIC,
    baseline_method TEXT NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    sample_size INTEGER NOT NULL,
    evidence_hash TEXT NOT NULL,
    computed_by TEXT DEFAULT 'STIG',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fss_log_asset_date
ON fhq_research.fss_computation_log(asset_id, computation_timestamp);

COMMENT ON TABLE fhq_research.fss_computation_log IS
'CEO-DIR-2026-101: Audit log for FSS computations with evidence hashes';


-- ============================================================================
-- SECTION 6: Log FSS Computation Trigger
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_research.log_fss_computation()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO fhq_research.fss_computation_log (
        asset_id,
        brier_actual,
        brier_ref,
        fss_value,
        baseline_method,
        period_start,
        period_end,
        sample_size,
        evidence_hash
    ) VALUES (
        NEW.asset_id,
        NEW.brier_actual,
        NEW.brier_ref,
        NEW.fss_value,
        NEW.baseline_method,
        lower(NEW.computed_for_period),
        upper(NEW.computed_for_period),
        NEW.sample_size,
        NEW.evidence_hash
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================================
-- SECTION 7: Register Migration
-- ============================================================================

INSERT INTO fhq_governance.governance_actions_log (
    action_type,
    action_target,
    action_target_type,
    initiated_by,
    decision,
    decision_rationale,
    metadata,
    signature,
    agent_id
) VALUES (
    'MIGRATION',
    'CEO-DIR-2026-101',
    'EPISTEMIC_FRAMEWORK',
    'STIG',
    'APPROVED',
    'Migration 270: FSS computation - GAP-COMP-001 resolved',
    jsonb_build_object(
        'migration', '270_fss_computation.sql',
        'phase', 'A2',
        'gap_resolved', 'GAP-COMP-001',
        'objects_created', ARRAY[
            'fhq_governance.prevent_temporal_contamination()',
            'fhq_research.compute_fss()',
            'fhq_research.backfill_fss()',
            'fhq_research.v_system_fss',
            'fhq_research.fss_computation_log'
        ],
        'temporal_integrity_enforced', true
    ),
    'Ed25519:STIG_MIGRATION_270',
    'STIG'
);

COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES (Run manually to verify migration)
-- ============================================================================
-- SELECT * FROM fhq_research.compute_fss('BTC-USD', '2026-01-01', '2026-01-19', 'NAIVE');
-- SELECT routine_name FROM information_schema.routines WHERE routine_schema = 'fhq_research' AND routine_name = 'compute_fss';
-- SELECT * FROM fhq_research.v_system_fss LIMIT 10;
