-- ============================================================================
-- Migration 271: LVI (Learning Velocity Index) Canonical Table
-- CEO-DIR-2026-101 Phase A2 - GAP-COMP-002 Remediation
-- ============================================================================
-- Purpose: Create canonical LVI table with regime-weighted decay computation
--
-- Constitutional Alignment: ADR-018, ADR-019, ADR-020
-- VEGA Gate: G3 Required
-- Generated By: STIG (EC-003_2026_PRODUCTION)
-- Generated At: 2026-01-19
--
-- LVI Formula: LVI_adjusted = Σ(Learning_Event × Regime_Weight × Decay_Factor) / T_total
-- Where:
--   - Learning_Event = 1 if forecast validated, 0 otherwise
--   - Regime_Weight = {STRESS: 1.0, GFI_HIGH: 0.9, NEUTRAL: 0.6, STABLE: 0.3}
--   - Decay_Factor = exp(-λ × days_since_event), λ = 0.05 (21-day half-life)
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECTION 1: LVI Canonical Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS fhq_governance.lvi_canonical (
    lvi_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id TEXT NOT NULL,
    lvi_value NUMERIC NOT NULL,
    regime_at_computation TEXT NOT NULL,
    regime_weight NUMERIC NOT NULL,
    decay_lambda NUMERIC DEFAULT 0.05,
    learning_events_counted INTEGER NOT NULL DEFAULT 0,
    total_events_in_window INTEGER NOT NULL DEFAULT 0,
    computation_method TEXT DEFAULT 'REGIME_WEIGHTED_DECAY',
    window_start DATE NOT NULL,
    window_end DATE NOT NULL,
    computed_at TIMESTAMPTZ DEFAULT NOW(),
    evidence_hash TEXT NOT NULL,
    computed_by TEXT DEFAULT 'STIG',
    CONSTRAINT lvi_value_range CHECK (lvi_value >= 0 AND lvi_value <= 1),
    CONSTRAINT regime_weight_range CHECK (regime_weight >= 0 AND regime_weight <= 1)
);

CREATE INDEX IF NOT EXISTS idx_lvi_canonical_asset
ON fhq_governance.lvi_canonical(asset_id, computed_at DESC);

CREATE INDEX IF NOT EXISTS idx_lvi_canonical_regime
ON fhq_governance.lvi_canonical(regime_at_computation, computed_at DESC);

COMMENT ON TABLE fhq_governance.lvi_canonical IS
'CEO-DIR-2026-101: Canonical Learning Velocity Index with regime-weighted decay.
LVI measures rate of forecast skill improvement under different market regimes.';


-- ============================================================================
-- SECTION 2: Regime Weight Configuration Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS fhq_governance.lvi_regime_weights (
    weight_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    regime_name TEXT UNIQUE NOT NULL,
    weight_value NUMERIC NOT NULL,
    rationale TEXT,
    effective_from TIMESTAMPTZ DEFAULT NOW(),
    effective_until TIMESTAMPTZ,
    approved_by TEXT DEFAULT 'CEO',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT weight_range CHECK (weight_value >= 0 AND weight_value <= 1)
);

-- Insert canonical regime weights per CEO-DIR-2026-101
INSERT INTO fhq_governance.lvi_regime_weights (regime_name, weight_value, rationale) VALUES
    ('STRESS', 1.0, 'Learning under stress is most valuable - maximum weight'),
    ('GFI_HIGH', 0.9, 'Geopolitical friction (GFI > 0.70) amplifies signal value'),
    ('NEUTRAL', 0.6, 'Moderate information value in neutral markets'),
    ('STABLE', 0.3, 'Low information value in trending/stable markets'),
    ('BULL', 0.3, 'Low information value in sustained bull markets'),
    ('BEAR', 0.7, 'Higher information value during bear markets'),
    ('BIFURCATED_LIQUIDITY', 0.85, 'High value - unusual market structure')
ON CONFLICT (regime_name) DO UPDATE SET
    weight_value = EXCLUDED.weight_value,
    rationale = EXCLUDED.rationale;

COMMENT ON TABLE fhq_governance.lvi_regime_weights IS
'CEO-DIR-2026-101: Regime weights for LVI computation.
Learning achieved during stress has higher value than learning during stable periods.';


-- ============================================================================
-- SECTION 3: LVI Computation Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.compute_lvi(
    p_asset_id TEXT DEFAULT NULL,
    p_window_days INTEGER DEFAULT 30,
    p_decay_lambda NUMERIC DEFAULT 0.05
)
RETURNS TABLE (
    asset_id TEXT,
    lvi_value NUMERIC,
    regime_at_computation TEXT,
    regime_weight NUMERIC,
    learning_events INTEGER,
    total_events INTEGER,
    window_start DATE,
    window_end DATE,
    evidence_hash TEXT
) AS $$
DECLARE
    v_window_start DATE := CURRENT_DATE - (p_window_days || ' days')::INTERVAL;
    v_window_end DATE := CURRENT_DATE;
BEGIN
    RETURN QUERY
    WITH forecast_outcomes AS (
        -- Get all forecasts with outcomes in the window
        SELECT
            bsl.asset_id,
            bsl.regime,
            bsl.forecast_timestamp::DATE AS forecast_date,
            bsl.squared_error,
            -- Learning event: Brier < 0.25 indicates skill above chance
            CASE WHEN bsl.squared_error < 0.25 THEN 1 ELSE 0 END AS learning_event,
            -- Days since event for decay calculation
            CURRENT_DATE - bsl.forecast_timestamp::DATE AS days_ago
        FROM fhq_governance.brier_score_ledger bsl
        WHERE (p_asset_id IS NULL OR bsl.asset_id = p_asset_id)
          AND bsl.forecast_timestamp::DATE BETWEEN v_window_start AND v_window_end
          AND bsl.squared_error IS NOT NULL
    ),
    regime_weighted AS (
        -- Apply regime weights and decay
        SELECT
            fo.asset_id,
            fo.regime,
            fo.learning_event,
            fo.days_ago,
            COALESCE(rw.weight_value, 0.5) AS regime_weight,
            -- Decay factor: exp(-λ × days)
            EXP(-p_decay_lambda * fo.days_ago) AS decay_factor
        FROM forecast_outcomes fo
        LEFT JOIN fhq_governance.lvi_regime_weights rw
            ON fo.regime = rw.regime_name
    ),
    aggregated AS (
        -- Aggregate LVI per asset
        SELECT
            rw.asset_id,
            -- LVI = Σ(Learning_Event × Regime_Weight × Decay) / Σ(Decay)
            CASE
                WHEN SUM(rw.decay_factor) > 0 THEN
                    SUM(rw.learning_event * rw.regime_weight * rw.decay_factor) / SUM(rw.decay_factor)
                ELSE 0
            END AS lvi_raw,
            MODE() WITHIN GROUP (ORDER BY rw.regime) AS primary_regime,
            AVG(rw.regime_weight) AS avg_regime_weight,
            SUM(rw.learning_event) AS learning_count,
            COUNT(*) AS total_count
        FROM regime_weighted rw
        GROUP BY rw.asset_id
    )
    SELECT
        ag.asset_id,
        LEAST(GREATEST(ag.lvi_raw, 0), 1)::NUMERIC AS lvi_value,  -- Clamp to [0,1]
        ag.primary_regime::TEXT,
        ag.avg_regime_weight::NUMERIC,
        ag.learning_count::INTEGER,
        ag.total_count::INTEGER,
        v_window_start,
        v_window_end,
        ('sha256:' || encode(sha256(
            (ag.asset_id || ag.lvi_raw::TEXT || ag.primary_regime || v_window_start::TEXT || v_window_end::TEXT)::bytea
        ), 'hex'))::TEXT AS evidence_hash
    FROM aggregated ag
    WHERE ag.total_count >= 5  -- Minimum sample size
    ORDER BY ag.asset_id;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fhq_governance.compute_lvi(TEXT, INTEGER, NUMERIC) IS
'CEO-DIR-2026-101: Computes Learning Velocity Index with regime-weighted decay.
LVI measures system learning rate, with higher weight for learning during stress.
Decay half-life at λ=0.05 is approximately 14 days.';


-- ============================================================================
-- SECTION 4: LVI Population Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.populate_lvi_canonical(
    p_window_days INTEGER DEFAULT 30
)
RETURNS INTEGER AS $$
DECLARE
    v_inserted INTEGER := 0;
    v_lvi_record RECORD;
BEGIN
    FOR v_lvi_record IN
        SELECT * FROM fhq_governance.compute_lvi(
            p_window_days := p_window_days
        )
    LOOP
        INSERT INTO fhq_governance.lvi_canonical (
            asset_id,
            lvi_value,
            regime_at_computation,
            regime_weight,
            learning_events_counted,
            total_events_in_window,
            window_start,
            window_end,
            evidence_hash
        ) VALUES (
            v_lvi_record.asset_id,
            v_lvi_record.lvi_value,
            v_lvi_record.regime_at_computation,
            v_lvi_record.regime_weight,
            v_lvi_record.learning_events,
            v_lvi_record.total_events,
            v_lvi_record.window_start,
            v_lvi_record.window_end,
            v_lvi_record.evidence_hash
        );
        v_inserted := v_inserted + 1;
    END LOOP;

    RETURN v_inserted;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_governance.populate_lvi_canonical(INTEGER) IS
'CEO-DIR-2026-101: Populates lvi_canonical table with computed LVI values';


-- ============================================================================
-- SECTION 5: System-Level LVI View
-- ============================================================================

CREATE OR REPLACE VIEW fhq_governance.v_system_lvi AS
SELECT
    lc.asset_id,
    lc.lvi_value,
    lc.regime_at_computation,
    lc.regime_weight,
    lc.learning_events_counted,
    lc.total_events_in_window,
    lc.window_start,
    lc.window_end,
    lc.computed_at,
    lc.evidence_hash,
    -- System-level aggregation
    AVG(lc.lvi_value) OVER () AS system_avg_lvi,
    -- Regime breakdown
    AVG(lc.lvi_value) OVER (PARTITION BY lc.regime_at_computation) AS regime_avg_lvi
FROM fhq_governance.lvi_canonical lc
WHERE lc.computed_at = (
    SELECT MAX(computed_at) FROM fhq_governance.lvi_canonical
    WHERE asset_id = lc.asset_id
);

COMMENT ON VIEW fhq_governance.v_system_lvi IS
'CEO-DIR-2026-101: Latest LVI values per asset with system and regime aggregations';


-- ============================================================================
-- SECTION 6: LVI History View (7-day rolling)
-- ============================================================================

CREATE OR REPLACE VIEW fhq_governance.v_lvi_rolling_7d AS
SELECT
    asset_id,
    DATE(computed_at) AS computation_date,
    AVG(lvi_value) AS avg_lvi,
    MIN(lvi_value) AS min_lvi,
    MAX(lvi_value) AS max_lvi,
    COUNT(*) AS observations
FROM fhq_governance.lvi_canonical
WHERE computed_at >= NOW() - INTERVAL '7 days'
GROUP BY asset_id, DATE(computed_at)
ORDER BY asset_id, computation_date;

COMMENT ON VIEW fhq_governance.v_lvi_rolling_7d IS
'CEO-DIR-2026-101: 7-day rolling LVI statistics per asset';


-- ============================================================================
-- SECTION 7: Register Migration
-- ============================================================================

INSERT INTO fhq_governance.governance_actions_log (
    action_type,
    action_target,
    action_target_type,
    initiated_by,
    decision,
    decision_rationale,
    metadata,
    signature,
    agent_id
) VALUES (
    'MIGRATION',
    'CEO-DIR-2026-101',
    'EPISTEMIC_FRAMEWORK',
    'STIG',
    'APPROVED',
    'Migration 271: LVI canonical - GAP-COMP-002 resolved',
    jsonb_build_object(
        'migration', '271_lvi_canonical.sql',
        'phase', 'A2',
        'gap_resolved', 'GAP-COMP-002',
        'objects_created', ARRAY[
            'fhq_governance.lvi_canonical',
            'fhq_governance.lvi_regime_weights',
            'fhq_governance.compute_lvi()',
            'fhq_governance.populate_lvi_canonical()',
            'fhq_governance.v_system_lvi',
            'fhq_governance.v_lvi_rolling_7d'
        ],
        'regime_weights_defined', true,
        'decay_lambda', 0.05
    ),
    'Ed25519:STIG_MIGRATION_271',
    'STIG'
);

COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES (Run manually to verify migration)
-- ============================================================================
-- SELECT * FROM fhq_governance.lvi_regime_weights;
-- SELECT * FROM fhq_governance.compute_lvi('BTC-USD', 30, 0.05);
-- SELECT fhq_governance.populate_lvi_canonical(30);
-- SELECT * FROM fhq_governance.v_system_lvi LIMIT 10;
