-- ============================================================================
-- Migration 272: Autonomy Clock State Table
-- CEO-DIR-2026-101 Phase A2 - GAP-STATE-002 Remediation
-- ============================================================================
-- Purpose: Create autonomy clock state machine for tracking consecutive
--          autonomous operation days without manual intervention
--
-- Constitutional Alignment: ADR-018 (observability metric, NOT Shared State)
-- VEGA Gate: G3 Required
-- Generated By: STIG (EC-003_2026_PRODUCTION)
-- Generated At: 2026-01-19
--
-- ADR-018 Boundary: This is an OBSERVABILITY METRIC, not a Shared State object
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECTION 1: Autonomy Clock State Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS fhq_governance.autonomy_clock_state (
    clock_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    consecutive_days INTEGER NOT NULL DEFAULT 0,
    state TEXT NOT NULL DEFAULT 'RUNNING',
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_tick_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reset_reason TEXT,
    reset_by TEXT,
    reset_at TIMESTAMPTZ,
    -- Metrics
    total_autonomous_days INTEGER NOT NULL DEFAULT 0,
    total_resets INTEGER NOT NULL DEFAULT 0,
    longest_streak INTEGER NOT NULL DEFAULT 0,
    current_streak_start DATE,
    -- Verification
    evidence_hash TEXT,
    CONSTRAINT valid_state CHECK (state IN ('RUNNING', 'PAUSED', 'RESET', 'MANUAL_OVERRIDE')),
    CONSTRAINT non_negative_days CHECK (consecutive_days >= 0)
);

CREATE INDEX IF NOT EXISTS idx_autonomy_clock_state
ON fhq_governance.autonomy_clock_state(state, updated_at DESC);

COMMENT ON TABLE fhq_governance.autonomy_clock_state IS
'CEO-DIR-2026-101: Autonomy clock tracking consecutive days of autonomous operation.
ADR-018 BOUNDARY: This is an observability metric, NOT a Shared State object.';


-- ============================================================================
-- SECTION 2: Autonomy Clock History Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS fhq_governance.autonomy_clock_history (
    history_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    clock_id UUID REFERENCES fhq_governance.autonomy_clock_state(clock_id),
    event_type TEXT NOT NULL,
    event_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    consecutive_days_before INTEGER,
    consecutive_days_after INTEGER,
    triggered_by TEXT,
    reason TEXT,
    evidence_hash TEXT,
    CONSTRAINT valid_event_type CHECK (event_type IN ('TICK', 'RESET', 'PAUSE', 'RESUME', 'MANUAL_OVERRIDE'))
);

CREATE INDEX IF NOT EXISTS idx_autonomy_clock_history_time
ON fhq_governance.autonomy_clock_history(event_timestamp DESC);

COMMENT ON TABLE fhq_governance.autonomy_clock_history IS
'CEO-DIR-2026-101: History of autonomy clock events for audit trail';


-- ============================================================================
-- SECTION 3: Initialize Autonomy Clock
-- ============================================================================

-- Insert initial clock state if not exists
INSERT INTO fhq_governance.autonomy_clock_state (
    consecutive_days,
    state,
    started_at,
    last_tick_at,
    current_streak_start,
    evidence_hash
)
SELECT
    0,
    'RUNNING',
    NOW(),
    NOW(),
    CURRENT_DATE,
    'sha256:' || encode(sha256(('INIT:' || NOW()::TEXT)::bytea), 'hex')
WHERE NOT EXISTS (
    SELECT 1 FROM fhq_governance.autonomy_clock_state
);


-- ============================================================================
-- SECTION 4: Autonomy Clock Tick Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.autonomy_clock_tick()
RETURNS JSONB AS $$
DECLARE
    v_clock RECORD;
    v_new_consecutive INTEGER;
    v_evidence TEXT;
BEGIN
    -- Get current clock state
    SELECT * INTO v_clock FROM fhq_governance.autonomy_clock_state
    ORDER BY updated_at DESC LIMIT 1;

    IF v_clock IS NULL THEN
        RAISE EXCEPTION 'Autonomy clock not initialized';
    END IF;

    -- Only tick if clock is RUNNING
    IF v_clock.state != 'RUNNING' THEN
        RETURN jsonb_build_object(
            'success', false,
            'reason', 'Clock is not in RUNNING state',
            'current_state', v_clock.state
        );
    END IF;

    -- Check if we've already ticked today
    IF v_clock.last_tick_at::DATE = CURRENT_DATE THEN
        RETURN jsonb_build_object(
            'success', false,
            'reason', 'Already ticked today',
            'consecutive_days', v_clock.consecutive_days
        );
    END IF;

    -- Increment consecutive days
    v_new_consecutive := v_clock.consecutive_days + 1;

    -- Generate evidence hash
    v_evidence := 'sha256:' || encode(sha256(
        (v_clock.clock_id::TEXT || v_new_consecutive::TEXT || CURRENT_DATE::TEXT)::bytea
    ), 'hex');

    -- Update clock state
    UPDATE fhq_governance.autonomy_clock_state
    SET
        consecutive_days = v_new_consecutive,
        last_tick_at = NOW(),
        updated_at = NOW(),
        total_autonomous_days = total_autonomous_days + 1,
        longest_streak = GREATEST(longest_streak, v_new_consecutive),
        evidence_hash = v_evidence
    WHERE clock_id = v_clock.clock_id;

    -- Log the tick
    INSERT INTO fhq_governance.autonomy_clock_history (
        clock_id,
        event_type,
        consecutive_days_before,
        consecutive_days_after,
        triggered_by,
        evidence_hash
    ) VALUES (
        v_clock.clock_id,
        'TICK',
        v_clock.consecutive_days,
        v_new_consecutive,
        'SYSTEM',
        v_evidence
    );

    RETURN jsonb_build_object(
        'success', true,
        'consecutive_days', v_new_consecutive,
        'total_autonomous_days', v_clock.total_autonomous_days + 1,
        'longest_streak', GREATEST(v_clock.longest_streak, v_new_consecutive),
        'evidence_hash', v_evidence
    );
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_governance.autonomy_clock_tick() IS
'CEO-DIR-2026-101: Daily tick for autonomy clock. Increments consecutive_days.
Called by LDOW daemon at end of successful autonomous operation day.';


-- ============================================================================
-- SECTION 5: Autonomy Clock Reset Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.autonomy_clock_reset(
    p_reason TEXT,
    p_triggered_by TEXT DEFAULT 'SYSTEM'
)
RETURNS JSONB AS $$
DECLARE
    v_clock RECORD;
    v_evidence TEXT;
BEGIN
    -- Get current clock state
    SELECT * INTO v_clock FROM fhq_governance.autonomy_clock_state
    ORDER BY updated_at DESC LIMIT 1;

    IF v_clock IS NULL THEN
        RAISE EXCEPTION 'Autonomy clock not initialized';
    END IF;

    -- Generate evidence hash
    v_evidence := 'sha256:' || encode(sha256(
        ('RESET:' || v_clock.clock_id::TEXT || p_reason || NOW()::TEXT)::bytea
    ), 'hex');

    -- Log the reset (before update)
    INSERT INTO fhq_governance.autonomy_clock_history (
        clock_id,
        event_type,
        consecutive_days_before,
        consecutive_days_after,
        triggered_by,
        reason,
        evidence_hash
    ) VALUES (
        v_clock.clock_id,
        'RESET',
        v_clock.consecutive_days,
        0,
        p_triggered_by,
        p_reason,
        v_evidence
    );

    -- Update clock state
    UPDATE fhq_governance.autonomy_clock_state
    SET
        consecutive_days = 0,
        state = 'RESET',
        updated_at = NOW(),
        reset_reason = p_reason,
        reset_by = p_triggered_by,
        reset_at = NOW(),
        total_resets = total_resets + 1,
        current_streak_start = NULL,
        evidence_hash = v_evidence
    WHERE clock_id = v_clock.clock_id;

    RETURN jsonb_build_object(
        'success', true,
        'previous_consecutive_days', v_clock.consecutive_days,
        'reset_reason', p_reason,
        'reset_by', p_triggered_by,
        'total_resets', v_clock.total_resets + 1,
        'evidence_hash', v_evidence
    );
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_governance.autonomy_clock_reset(TEXT, TEXT) IS
'CEO-DIR-2026-101: Reset autonomy clock to zero. Called on manual intervention.';


-- ============================================================================
-- SECTION 6: Autonomy Clock Resume Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.autonomy_clock_resume()
RETURNS JSONB AS $$
DECLARE
    v_clock RECORD;
    v_evidence TEXT;
BEGIN
    -- Get current clock state
    SELECT * INTO v_clock FROM fhq_governance.autonomy_clock_state
    ORDER BY updated_at DESC LIMIT 1;

    IF v_clock IS NULL THEN
        RAISE EXCEPTION 'Autonomy clock not initialized';
    END IF;

    IF v_clock.state = 'RUNNING' THEN
        RETURN jsonb_build_object(
            'success', false,
            'reason', 'Clock is already running'
        );
    END IF;

    -- Generate evidence hash
    v_evidence := 'sha256:' || encode(sha256(
        ('RESUME:' || v_clock.clock_id::TEXT || NOW()::TEXT)::bytea
    ), 'hex');

    -- Update clock state
    UPDATE fhq_governance.autonomy_clock_state
    SET
        state = 'RUNNING',
        updated_at = NOW(),
        current_streak_start = CURRENT_DATE,
        evidence_hash = v_evidence
    WHERE clock_id = v_clock.clock_id;

    -- Log the resume
    INSERT INTO fhq_governance.autonomy_clock_history (
        clock_id,
        event_type,
        consecutive_days_before,
        consecutive_days_after,
        triggered_by,
        evidence_hash
    ) VALUES (
        v_clock.clock_id,
        'RESUME',
        v_clock.consecutive_days,
        v_clock.consecutive_days,
        'SYSTEM',
        v_evidence
    );

    RETURN jsonb_build_object(
        'success', true,
        'consecutive_days', v_clock.consecutive_days,
        'new_streak_start', CURRENT_DATE,
        'evidence_hash', v_evidence
    );
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_governance.autonomy_clock_resume() IS
'CEO-DIR-2026-101: Resume autonomy clock after reset or pause.';


-- ============================================================================
-- SECTION 7: Autonomy Clock Status View
-- ============================================================================

CREATE OR REPLACE VIEW fhq_governance.v_autonomy_clock_status AS
SELECT
    clock_id,
    consecutive_days,
    state,
    started_at,
    last_tick_at,
    updated_at,
    total_autonomous_days,
    total_resets,
    longest_streak,
    current_streak_start,
    reset_reason,
    reset_by,
    reset_at,
    evidence_hash,
    -- Derived metrics
    CASE
        WHEN state = 'RUNNING' THEN
            CURRENT_DATE - current_streak_start
        ELSE NULL
    END AS days_since_streak_start,
    ROUND(
        CASE
            WHEN total_autonomous_days > 0 THEN
                (longest_streak::NUMERIC / total_autonomous_days) * 100
            ELSE 0
        END, 2
    ) AS streak_efficiency_pct
FROM fhq_governance.autonomy_clock_state
ORDER BY updated_at DESC
LIMIT 1;

COMMENT ON VIEW fhq_governance.v_autonomy_clock_status IS
'CEO-DIR-2026-101: Current autonomy clock status with derived metrics';


-- ============================================================================
-- SECTION 8: Register Migration
-- ============================================================================

INSERT INTO fhq_governance.governance_actions_log (
    action_type,
    action_target,
    action_target_type,
    initiated_by,
    decision,
    decision_rationale,
    metadata,
    signature,
    agent_id
) VALUES (
    'MIGRATION',
    'CEO-DIR-2026-101',
    'EPISTEMIC_FRAMEWORK',
    'STIG',
    'APPROVED',
    'Migration 272: Autonomy clock state - GAP-STATE-002 resolved',
    jsonb_build_object(
        'migration', '272_autonomy_clock_state.sql',
        'phase', 'A2',
        'gap_resolved', 'GAP-STATE-002',
        'objects_created', ARRAY[
            'fhq_governance.autonomy_clock_state',
            'fhq_governance.autonomy_clock_history',
            'fhq_governance.autonomy_clock_tick()',
            'fhq_governance.autonomy_clock_reset()',
            'fhq_governance.autonomy_clock_resume()',
            'fhq_governance.v_autonomy_clock_status'
        ],
        'adr_018_boundary', 'OBSERVABILITY_METRIC (not Shared State)'
    ),
    'Ed25519:STIG_MIGRATION_272',
    'STIG'
);

COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES (Run manually to verify migration)
-- ============================================================================
-- SELECT * FROM fhq_governance.v_autonomy_clock_status;
-- SELECT fhq_governance.autonomy_clock_tick();
-- SELECT * FROM fhq_governance.autonomy_clock_history ORDER BY event_timestamp DESC LIMIT 10;
