-- ============================================================================
-- Migration 273: Calibration Bins Table (ADR-019)
-- CEO-DIR-2026-101 Phase A2 - GAP-COMP-003 Remediation
-- ============================================================================
-- Purpose: Create calibration bins table for reliability diagram rendering
--          Dashboard displays server-side computed values with hash-of-truth
--
-- Constitutional Alignment: ADR-019 (Dashboard Hash-of-Truth)
-- VEGA Gate: G3 Required
-- Generated By: STIG (EC-003_2026_PRODUCTION)
-- Generated At: 2026-01-19
--
-- ADR-019 Rule: UI surfaces server-side computed values plus verification hash.
--               No frontend arithmetic. Dashboard renders canonical DB values.
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECTION 1: Calibration Bins Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS fhq_governance.calibration_bins (
    bin_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id TEXT,  -- NULL for system-wide
    forecast_type TEXT NOT NULL,
    bin_lower NUMERIC NOT NULL,
    bin_upper NUMERIC NOT NULL,
    forecast_count INTEGER NOT NULL DEFAULT 0,
    observed_frequency NUMERIC NOT NULL DEFAULT 0,
    mean_forecast NUMERIC NOT NULL DEFAULT 0,
    calibration_error NUMERIC GENERATED ALWAYS AS (ABS(observed_frequency - mean_forecast)) STORED,
    -- Brier decomposition components
    reliability_component NUMERIC,  -- Calibration error weighted by bin size
    resolution_component NUMERIC,   -- Deviation from base rate
    -- Metadata
    computed_for_period DATERANGE NOT NULL,
    sample_size INTEGER NOT NULL DEFAULT 0,
    computed_at TIMESTAMPTZ DEFAULT NOW(),
    computed_by TEXT DEFAULT 'STIG',
    evidence_hash TEXT NOT NULL,
    -- Constraints
    CONSTRAINT valid_bin_range CHECK (bin_lower >= 0 AND bin_upper <= 1 AND bin_lower < bin_upper),
    CONSTRAINT valid_frequency CHECK (observed_frequency >= 0 AND observed_frequency <= 1),
    CONSTRAINT valid_mean_forecast CHECK (mean_forecast >= 0 AND mean_forecast <= 1)
);

CREATE INDEX IF NOT EXISTS idx_calibration_bins_type
ON fhq_governance.calibration_bins(forecast_type, computed_at DESC);

CREATE INDEX IF NOT EXISTS idx_calibration_bins_asset
ON fhq_governance.calibration_bins(asset_id, forecast_type) WHERE asset_id IS NOT NULL;

COMMENT ON TABLE fhq_governance.calibration_bins IS
'CEO-DIR-2026-101 / ADR-019: Calibration bins for reliability diagram rendering.
Dashboard displays these server-side computed values with hash-of-truth visible.
No frontend arithmetic permitted.';


-- ============================================================================
-- SECTION 2: Standard Bin Configuration
-- ============================================================================

CREATE TABLE IF NOT EXISTS fhq_governance.calibration_bin_config (
    config_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    config_name TEXT UNIQUE NOT NULL,
    bin_count INTEGER NOT NULL DEFAULT 10,
    bin_boundaries NUMERIC[] NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT valid_bin_count CHECK (bin_count >= 5 AND bin_count <= 20)
);

-- Insert standard 10-bin configuration for reliability diagrams
INSERT INTO fhq_governance.calibration_bin_config (config_name, bin_count, bin_boundaries)
VALUES (
    'STANDARD_10_BINS',
    10,
    ARRAY[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
)
ON CONFLICT (config_name) DO NOTHING;

COMMENT ON TABLE fhq_governance.calibration_bin_config IS
'CEO-DIR-2026-101: Configuration for calibration bin boundaries';


-- ============================================================================
-- SECTION 3: Calibration Bins Computation Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.compute_calibration_bins(
    p_forecast_type TEXT DEFAULT 'PRICE_DIRECTION',
    p_asset_id TEXT DEFAULT NULL,
    p_start_date DATE DEFAULT NULL,
    p_end_date DATE DEFAULT NULL,
    p_config_name TEXT DEFAULT 'STANDARD_10_BINS'
)
RETURNS TABLE (
    bin_lower NUMERIC,
    bin_upper NUMERIC,
    forecast_count INTEGER,
    observed_frequency NUMERIC,
    mean_forecast NUMERIC,
    calibration_error NUMERIC,
    evidence_hash TEXT
) AS $$
DECLARE
    v_boundaries NUMERIC[];
    v_start DATE := COALESCE(p_start_date, CURRENT_DATE - INTERVAL '30 days');
    v_end DATE := COALESCE(p_end_date, CURRENT_DATE);
    i INTEGER;
BEGIN
    -- Get bin boundaries from config
    SELECT bin_boundaries INTO v_boundaries
    FROM fhq_governance.calibration_bin_config
    WHERE config_name = p_config_name AND is_active = true;

    IF v_boundaries IS NULL THEN
        v_boundaries := ARRAY[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0];
    END IF;

    -- Compute bins
    RETURN QUERY
    WITH binned_forecasts AS (
        SELECT
            bsl.forecast_probability,
            bsl.actual_outcome,
            -- Assign to bin
            (SELECT MAX(b) FROM unnest(v_boundaries) b WHERE b <= bsl.forecast_probability) AS bin_start
        FROM fhq_governance.brier_score_ledger bsl
        WHERE bsl.forecast_type = p_forecast_type
          AND (p_asset_id IS NULL OR bsl.asset_id = p_asset_id)
          AND bsl.forecast_timestamp::DATE BETWEEN v_start AND v_end
          AND bsl.forecast_probability IS NOT NULL
          AND bsl.actual_outcome IS NOT NULL
    ),
    aggregated AS (
        SELECT
            bf.bin_start,
            (SELECT MIN(b) FROM unnest(v_boundaries) b WHERE b > bf.bin_start) AS bin_end,
            COUNT(*) AS cnt,
            AVG(CASE WHEN bf.actual_outcome THEN 1.0 ELSE 0.0 END) AS obs_freq,
            AVG(bf.forecast_probability) AS mean_fcst
        FROM binned_forecasts bf
        WHERE bf.bin_start IS NOT NULL
        GROUP BY bf.bin_start
    )
    SELECT
        ag.bin_start::NUMERIC,
        COALESCE(ag.bin_end, 1.0)::NUMERIC,
        ag.cnt::INTEGER,
        ROUND(ag.obs_freq, 4)::NUMERIC,
        ROUND(ag.mean_fcst, 4)::NUMERIC,
        ROUND(ABS(ag.obs_freq - ag.mean_fcst), 4)::NUMERIC,
        ('sha256:' || encode(sha256(
            (p_forecast_type || COALESCE(p_asset_id, 'SYSTEM') || ag.bin_start::TEXT || ag.cnt::TEXT || ag.obs_freq::TEXT)::bytea
        ), 'hex'))::TEXT
    FROM aggregated ag
    ORDER BY ag.bin_start;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fhq_governance.compute_calibration_bins(TEXT, TEXT, DATE, DATE, TEXT) IS
'CEO-DIR-2026-101 / ADR-019: Computes calibration bins for reliability diagrams.
Returns bins with observed_frequency vs mean_forecast for calibration assessment.';


-- ============================================================================
-- SECTION 4: Populate Calibration Bins Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.populate_calibration_bins(
    p_forecast_type TEXT DEFAULT 'PRICE_DIRECTION',
    p_asset_id TEXT DEFAULT NULL,
    p_start_date DATE DEFAULT NULL,
    p_end_date DATE DEFAULT NULL
)
RETURNS INTEGER AS $$
DECLARE
    v_inserted INTEGER := 0;
    v_bin_record RECORD;
    v_period DATERANGE;
    v_start DATE := COALESCE(p_start_date, CURRENT_DATE - INTERVAL '30 days');
    v_end DATE := COALESCE(p_end_date, CURRENT_DATE);
BEGIN
    v_period := daterange(v_start, v_end, '[]');

    -- Delete existing bins for this period/type/asset combination
    DELETE FROM fhq_governance.calibration_bins
    WHERE forecast_type = p_forecast_type
      AND ((p_asset_id IS NULL AND asset_id IS NULL) OR asset_id = p_asset_id)
      AND computed_for_period && v_period;

    -- Insert new bins
    FOR v_bin_record IN
        SELECT * FROM fhq_governance.compute_calibration_bins(
            p_forecast_type,
            p_asset_id,
            v_start,
            v_end
        )
    LOOP
        INSERT INTO fhq_governance.calibration_bins (
            asset_id,
            forecast_type,
            bin_lower,
            bin_upper,
            forecast_count,
            observed_frequency,
            mean_forecast,
            computed_for_period,
            sample_size,
            evidence_hash
        ) VALUES (
            p_asset_id,
            p_forecast_type,
            v_bin_record.bin_lower,
            v_bin_record.bin_upper,
            v_bin_record.forecast_count,
            v_bin_record.observed_frequency,
            v_bin_record.mean_forecast,
            v_period,
            v_bin_record.forecast_count,
            v_bin_record.evidence_hash
        );
        v_inserted := v_inserted + 1;
    END LOOP;

    RETURN v_inserted;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_governance.populate_calibration_bins(TEXT, TEXT, DATE, DATE) IS
'CEO-DIR-2026-101 / ADR-019: Populates calibration_bins table for dashboard rendering';


-- ============================================================================
-- SECTION 5: Reliability Diagram View (ADR-019 Dashboard)
-- ============================================================================

CREATE OR REPLACE VIEW fhq_governance.v_reliability_diagram AS
SELECT
    cb.bin_id,
    cb.asset_id,
    cb.forecast_type,
    cb.bin_lower,
    cb.bin_upper,
    -- Bin midpoint for plotting
    (cb.bin_lower + cb.bin_upper) / 2 AS bin_midpoint,
    cb.forecast_count,
    cb.observed_frequency,
    cb.mean_forecast,
    cb.calibration_error,
    -- Perfect calibration line comparison
    (cb.bin_lower + cb.bin_upper) / 2 AS perfect_calibration,
    cb.observed_frequency - ((cb.bin_lower + cb.bin_upper) / 2) AS deviation_from_perfect,
    cb.computed_for_period,
    cb.computed_at,
    cb.evidence_hash,
    -- ADR-019: Hash-of-truth visible to dashboard
    'VERIFIED: ' || cb.evidence_hash AS dashboard_verification_label
FROM fhq_governance.calibration_bins cb
WHERE cb.computed_at = (
    SELECT MAX(computed_at)
    FROM fhq_governance.calibration_bins
    WHERE forecast_type = cb.forecast_type
      AND ((cb.asset_id IS NULL AND asset_id IS NULL) OR asset_id = cb.asset_id)
)
ORDER BY cb.forecast_type, cb.asset_id NULLS FIRST, cb.bin_lower;

COMMENT ON VIEW fhq_governance.v_reliability_diagram IS
'CEO-DIR-2026-101 / ADR-019: Dashboard-ready reliability diagram data.
Hash-of-truth (evidence_hash) visible for each bin per ADR-019 requirement.';


-- ============================================================================
-- SECTION 6: System Calibration Summary View
-- ============================================================================

CREATE OR REPLACE VIEW fhq_governance.v_system_calibration_summary AS
SELECT
    forecast_type,
    asset_id,
    -- Weighted mean calibration error (by bin size)
    SUM(calibration_error * forecast_count) / NULLIF(SUM(forecast_count), 0) AS weighted_calibration_error,
    -- Total sample size
    SUM(forecast_count) AS total_forecasts,
    -- Bin count
    COUNT(*) AS bin_count,
    -- Max deviation
    MAX(calibration_error) AS max_bin_error,
    -- Period
    MIN(lower(computed_for_period)) AS period_start,
    MAX(upper(computed_for_period)) AS period_end,
    -- Latest computation
    MAX(computed_at) AS latest_computed_at
FROM fhq_governance.calibration_bins
GROUP BY forecast_type, asset_id
ORDER BY forecast_type, asset_id NULLS FIRST;

COMMENT ON VIEW fhq_governance.v_system_calibration_summary IS
'CEO-DIR-2026-101: System-level calibration summary across forecast types';


-- ============================================================================
-- SECTION 7: Register Migration
-- ============================================================================

INSERT INTO fhq_governance.governance_actions_log (
    action_type,
    action_target,
    action_target_type,
    initiated_by,
    decision,
    decision_rationale,
    metadata,
    signature,
    agent_id
) VALUES (
    'MIGRATION',
    'CEO-DIR-2026-101',
    'EPISTEMIC_FRAMEWORK',
    'STIG',
    'APPROVED',
    'Migration 273: Calibration bins - GAP-COMP-003 resolved',
    jsonb_build_object(
        'migration', '273_calibration_bins.sql',
        'phase', 'A2',
        'gap_resolved', 'GAP-COMP-003',
        'objects_created', ARRAY[
            'fhq_governance.calibration_bins',
            'fhq_governance.calibration_bin_config',
            'fhq_governance.compute_calibration_bins()',
            'fhq_governance.populate_calibration_bins()',
            'fhq_governance.v_reliability_diagram',
            'fhq_governance.v_system_calibration_summary'
        ],
        'adr_019_compliance', 'Dashboard hash-of-truth implemented'
    ),
    'Ed25519:STIG_MIGRATION_273',
    'STIG'
);

COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES (Run manually to verify migration)
-- ============================================================================
-- SELECT * FROM fhq_governance.calibration_bin_config;
-- SELECT * FROM fhq_governance.compute_calibration_bins('PRICE_DIRECTION', NULL, '2026-01-01', '2026-01-19');
-- SELECT fhq_governance.populate_calibration_bins('PRICE_DIRECTION');
-- SELECT * FROM fhq_governance.v_reliability_diagram;
-- SELECT * FROM fhq_governance.v_system_calibration_summary;
