-- ============================================================================
-- Migration 274: Regime Shadow Tracking (fhq_provisional)
-- CEO-DIR-2026-101 Phase A2 - GAP-STATE-001 Remediation (Shadow Mode)
-- ============================================================================
-- Purpose: Create provisional schema and shadow tracking for BIFURCATED_LIQUIDITY
--          Allows Day N/M evidence collection without contaminating canonical regime_states
--
-- Constitutional Alignment: ADR-018 (Shared State boundary)
-- VEGA Gate: None (provisional data, not canonical until G4 promotion)
-- Generated By: STIG (EC-003_2026_PRODUCTION)
-- Generated At: 2026-01-19
--
-- Shadow Mode Rules:
-- 1. CEIO MAY populate fhq_provisional.regime_shadow_tracking during Phase A1
-- 2. Shadow data is NOT used for decision-making until G4 promotion
-- 3. Upon G4 approval, VEGA migrates shadow records to canonical regime_states
-- 4. Shadow table retains full history for audit trail
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECTION 1: Create Provisional Schema
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS fhq_provisional;

COMMENT ON SCHEMA fhq_provisional IS
'CEO-DIR-2026-101: Provisional data schema for shadow tracking and pre-G4 observations.
Data here is NOT canonical and NOT used for decision-making until promoted.';


-- ============================================================================
-- SECTION 2: Regime Shadow Tracking Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS fhq_provisional.regime_shadow_tracking (
    shadow_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    regime_name TEXT NOT NULL,
    trigger_conditions JSONB NOT NULL,
    day_n INTEGER NOT NULL,
    day_m INTEGER NOT NULL,
    observation_date DATE NOT NULL,
    observed_by TEXT NOT NULL,
    evidence_hash TEXT NOT NULL,
    -- Shadow state
    is_provisional BOOLEAN DEFAULT TRUE,
    promoted_to_canonical BOOLEAN DEFAULT FALSE,
    promoted_at TIMESTAMPTZ,
    promoted_by TEXT,
    promotion_evidence_id UUID,
    -- Observation metadata
    observation_metadata JSONB,
    confidence_score NUMERIC,
    supporting_indicators JSONB,
    -- Audit trail
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    -- Constraints
    CONSTRAINT valid_day_counter CHECK (day_n >= 0 AND day_m >= day_n),
    CONSTRAINT valid_confidence CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1))
);

CREATE INDEX IF NOT EXISTS idx_regime_shadow_name_date
ON fhq_provisional.regime_shadow_tracking(regime_name, observation_date);

CREATE INDEX IF NOT EXISTS idx_regime_shadow_provisional
ON fhq_provisional.regime_shadow_tracking(is_provisional, promoted_to_canonical);

COMMENT ON TABLE fhq_provisional.regime_shadow_tracking IS
'CEO-DIR-2026-101: Shadow tracking for provisional regimes (e.g., BIFURCATED_LIQUIDITY).
This data is NOT used for decision-making until G4 promotion to canonical regime_states.';


-- ============================================================================
-- SECTION 3: Shadow Observation Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_provisional.record_shadow_observation(
    p_regime_name TEXT,
    p_trigger_conditions JSONB,
    p_day_n INTEGER,
    p_day_m INTEGER,
    p_observation_date DATE,
    p_observed_by TEXT,
    p_metadata JSONB DEFAULT NULL,
    p_confidence NUMERIC DEFAULT NULL,
    p_indicators JSONB DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
    v_shadow_id UUID;
    v_evidence_hash TEXT;
BEGIN
    -- Generate evidence hash
    v_evidence_hash := 'sha256:' || encode(sha256(
        (p_regime_name || p_trigger_conditions::TEXT || p_day_n::TEXT || p_day_m::TEXT ||
         p_observation_date::TEXT || NOW()::TEXT)::bytea
    ), 'hex');

    INSERT INTO fhq_provisional.regime_shadow_tracking (
        regime_name,
        trigger_conditions,
        day_n,
        day_m,
        observation_date,
        observed_by,
        evidence_hash,
        observation_metadata,
        confidence_score,
        supporting_indicators
    ) VALUES (
        p_regime_name,
        p_trigger_conditions,
        p_day_n,
        p_day_m,
        p_observation_date,
        p_observed_by,
        v_evidence_hash,
        p_metadata,
        p_confidence,
        p_indicators
    ) RETURNING shadow_id INTO v_shadow_id;

    RETURN v_shadow_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_provisional.record_shadow_observation IS
'CEO-DIR-2026-101: Records a shadow regime observation. NOT used for decisions until G4 promotion.';


-- ============================================================================
-- SECTION 4: Shadow Promotion Function (G4 Required)
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_provisional.promote_shadow_to_canonical(
    p_shadow_id UUID,
    p_promoted_by TEXT,
    p_g4_evidence_id UUID
)
RETURNS JSONB AS $$
DECLARE
    v_shadow RECORD;
    v_result JSONB;
BEGIN
    -- Get shadow record
    SELECT * INTO v_shadow
    FROM fhq_provisional.regime_shadow_tracking
    WHERE shadow_id = p_shadow_id;

    IF v_shadow IS NULL THEN
        RETURN jsonb_build_object(
            'success', false,
            'error', 'Shadow record not found'
        );
    END IF;

    IF v_shadow.promoted_to_canonical THEN
        RETURN jsonb_build_object(
            'success', false,
            'error', 'Already promoted to canonical'
        );
    END IF;

    -- Verify G4 evidence exists (would normally check governance_actions_log)
    -- For now, just require the evidence ID
    IF p_g4_evidence_id IS NULL THEN
        RETURN jsonb_build_object(
            'success', false,
            'error', 'G4 evidence ID required for promotion'
        );
    END IF;

    -- Update shadow record as promoted
    UPDATE fhq_provisional.regime_shadow_tracking
    SET
        is_provisional = FALSE,
        promoted_to_canonical = TRUE,
        promoted_at = NOW(),
        promoted_by = p_promoted_by,
        promotion_evidence_id = p_g4_evidence_id,
        updated_at = NOW()
    WHERE shadow_id = p_shadow_id;

    -- Note: Actual insertion into canonical regime_states would happen here
    -- but requires G4-approved schema changes to regime_states table
    -- For now, we just mark as promoted in shadow table

    RETURN jsonb_build_object(
        'success', true,
        'shadow_id', p_shadow_id,
        'regime_name', v_shadow.regime_name,
        'promoted_at', NOW(),
        'promoted_by', p_promoted_by,
        'g4_evidence_id', p_g4_evidence_id,
        'note', 'Shadow record promoted. Canonical regime_states insertion requires separate G4 migration.'
    );
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_provisional.promote_shadow_to_canonical IS
'CEO-DIR-2026-101: Promotes shadow observation to canonical status. REQUIRES G4 evidence.';


-- ============================================================================
-- SECTION 5: Shadow Regime Status View
-- ============================================================================

CREATE OR REPLACE VIEW fhq_provisional.v_shadow_regime_status AS
SELECT
    regime_name,
    COUNT(*) AS total_observations,
    MAX(day_n) AS latest_day_n,
    MAX(day_m) AS latest_day_m,
    MIN(observation_date) AS first_observation,
    MAX(observation_date) AS latest_observation,
    COUNT(*) FILTER (WHERE is_provisional) AS provisional_count,
    COUNT(*) FILTER (WHERE promoted_to_canonical) AS promoted_count,
    AVG(confidence_score) AS avg_confidence,
    array_agg(DISTINCT observed_by) AS observers
FROM fhq_provisional.regime_shadow_tracking
GROUP BY regime_name
ORDER BY regime_name;

COMMENT ON VIEW fhq_provisional.v_shadow_regime_status IS
'CEO-DIR-2026-101: Summary of shadow regime observations';


-- ============================================================================
-- SECTION 6: BIFURCATED_LIQUIDITY Day N/M View
-- ============================================================================

CREATE OR REPLACE VIEW fhq_provisional.v_bifurcated_liquidity_tracking AS
SELECT
    shadow_id,
    day_n,
    day_m,
    observation_date,
    observed_by,
    trigger_conditions,
    confidence_score,
    supporting_indicators,
    is_provisional,
    promoted_to_canonical,
    evidence_hash,
    created_at,
    -- Day N/M display format
    'Day ' || day_n || '/' || day_m AS day_display,
    -- Progress percentage
    ROUND((day_n::NUMERIC / NULLIF(day_m, 0)) * 100, 1) AS progress_pct
FROM fhq_provisional.regime_shadow_tracking
WHERE regime_name = 'BIFURCATED_LIQUIDITY'
ORDER BY observation_date DESC, created_at DESC;

COMMENT ON VIEW fhq_provisional.v_bifurcated_liquidity_tracking IS
'CEO-DIR-2026-101: BIFURCATED_LIQUIDITY Day N/M tracking (shadow mode until G4 promotion)';


-- ============================================================================
-- SECTION 7: Shadow Audit Log
-- ============================================================================

CREATE TABLE IF NOT EXISTS fhq_provisional.shadow_audit_log (
    log_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    action_type TEXT NOT NULL,
    shadow_id UUID REFERENCES fhq_provisional.regime_shadow_tracking(shadow_id),
    regime_name TEXT NOT NULL,
    details JSONB,
    performed_by TEXT NOT NULL,
    performed_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT valid_action_type CHECK (action_type IN ('CREATE', 'UPDATE', 'PROMOTE', 'ARCHIVE'))
);

CREATE INDEX IF NOT EXISTS idx_shadow_audit_time
ON fhq_provisional.shadow_audit_log(performed_at DESC);

COMMENT ON TABLE fhq_provisional.shadow_audit_log IS
'CEO-DIR-2026-101: Audit log for shadow regime operations';


-- ============================================================================
-- SECTION 8: Shadow Observation Trigger (Audit Logging)
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_provisional.log_shadow_change()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO fhq_provisional.shadow_audit_log (
            action_type, shadow_id, regime_name, details, performed_by
        ) VALUES (
            'CREATE',
            NEW.shadow_id,
            NEW.regime_name,
            jsonb_build_object(
                'day_n', NEW.day_n,
                'day_m', NEW.day_m,
                'observation_date', NEW.observation_date
            ),
            NEW.observed_by
        );
    ELSIF TG_OP = 'UPDATE' THEN
        IF NEW.promoted_to_canonical AND NOT OLD.promoted_to_canonical THEN
            INSERT INTO fhq_provisional.shadow_audit_log (
                action_type, shadow_id, regime_name, details, performed_by
            ) VALUES (
                'PROMOTE',
                NEW.shadow_id,
                NEW.regime_name,
                jsonb_build_object(
                    'promoted_at', NEW.promoted_at,
                    'promotion_evidence_id', NEW.promotion_evidence_id
                ),
                NEW.promoted_by
            );
        ELSE
            INSERT INTO fhq_provisional.shadow_audit_log (
                action_type, shadow_id, regime_name, details, performed_by
            ) VALUES (
                'UPDATE',
                NEW.shadow_id,
                NEW.regime_name,
                jsonb_build_object(
                    'day_n', NEW.day_n,
                    'day_m', NEW.day_m,
                    'confidence_score', NEW.confidence_score
                ),
                COALESCE(NEW.observed_by, 'SYSTEM')
            );
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_shadow_audit
AFTER INSERT OR UPDATE ON fhq_provisional.regime_shadow_tracking
FOR EACH ROW EXECUTE FUNCTION fhq_provisional.log_shadow_change();


-- ============================================================================
-- SECTION 9: Register Migration
-- ============================================================================

INSERT INTO fhq_governance.governance_actions_log (
    action_type,
    action_target,
    action_target_type,
    initiated_by,
    decision,
    decision_rationale,
    metadata,
    signature,
    agent_id
) VALUES (
    'MIGRATION',
    'CEO-DIR-2026-101',
    'EPISTEMIC_FRAMEWORK',
    'STIG',
    'APPROVED',
    'Migration 274: Regime shadow tracking - GAP-STATE-001 addressed',
    jsonb_build_object(
        'migration', '274_regime_shadow_tracking.sql',
        'phase', 'A2',
        'gap_addressed', 'GAP-STATE-001 (Shadow Mode)',
        'objects_created', ARRAY[
            'fhq_provisional (schema)',
            'fhq_provisional.regime_shadow_tracking',
            'fhq_provisional.shadow_audit_log',
            'fhq_provisional.record_shadow_observation()',
            'fhq_provisional.promote_shadow_to_canonical()',
            'fhq_provisional.v_shadow_regime_status',
            'fhq_provisional.v_bifurcated_liquidity_tracking'
        ],
        'shadow_mode_rules', ARRAY[
            'CEIO MAY populate during Phase A1',
            'Shadow data NOT used for decision-making until G4 promotion',
            'G4 approval required for canonical promotion',
            'Shadow table retains full history for audit trail'
        ]
    ),
    'Ed25519:STIG_MIGRATION_274',
    'STIG'
);

COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES (Run manually to verify migration)
-- ============================================================================
-- SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'fhq_provisional';
-- SELECT fhq_provisional.record_shadow_observation(
--     'BIFURCATED_LIQUIDITY',
--     '{"trigger": "liquidity_divergence", "threshold": 0.3}'::jsonb,
--     4,
--     5,
--     '2026-01-19',
--     'CEIO'
-- );
-- SELECT * FROM fhq_provisional.v_bifurcated_liquidity_tracking;
-- SELECT * FROM fhq_provisional.v_shadow_regime_status;
