-- ============================================================================
-- Migration 275: Ex-Ante Regime Beliefs (Epistemic Upgrade)
-- CEO-DIR-2026-101 Phase C Prerequisite - GAP-REGIME-001 Remediation
-- ============================================================================
-- Purpose: Transform regime from classification (label) to epistemic belief
--          (testable forecast with ex-ante timestamp and probability distribution)
--
-- CEO Mandate: "Regime must become a forecastable belief, not just a state"
--
-- This enables:
--   - Regime Brier Score (calibration of regime beliefs)
--   - Regime-specific LVI (learning velocity per regime type)
--   - Regime hallucination detection
--
-- Constitutional Alignment: ADR-017, ADR-018, ADR-019, ADR-020
-- VEGA Gate: G3 Required
-- Generated By: STIG (EC-003_2026_PRODUCTION)
-- Generated At: 2026-01-19
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECTION 1: Ex-Ante Regime Beliefs Table
-- ============================================================================
-- Core principle: A regime belief is a forecast about future market state
-- It must be timestamped BEFORE the observation window it predicts

CREATE TABLE IF NOT EXISTS fhq_governance.ex_ante_regime_beliefs (
    belief_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- What is being predicted
    asset_id TEXT NOT NULL,
    predicted_regime TEXT NOT NULL,

    -- Probability distribution over regimes
    regime_probabilities JSONB NOT NULL,
    -- Example: {"BULL": 0.15, "BEAR": 0.10, "NEUTRAL": 0.20, "STRESS": 0.55}

    -- Temporal integrity (ex-ante requirement)
    belief_formed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    prediction_horizon_hours INTEGER NOT NULL DEFAULT 24,
    prediction_target_date DATE NOT NULL,

    -- Outcome (filled when resolved)
    actual_regime TEXT,
    outcome_observed_at TIMESTAMPTZ,

    -- Brier-compatible scoring
    regime_brier_score NUMERIC,
    belief_was_correct BOOLEAN,

    -- Confidence and calibration
    max_probability NUMERIC NOT NULL,
    entropy NUMERIC,  -- Higher entropy = more uncertainty

    -- Lineage
    model_version TEXT,
    generating_agent TEXT NOT NULL DEFAULT 'FINN',
    evidence_hash TEXT NOT NULL,

    -- Audit
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- Constraints
    CONSTRAINT valid_max_prob CHECK (max_probability >= 0 AND max_probability <= 1),
    CONSTRAINT ex_ante_temporal_integrity CHECK (
        belief_formed_at < (prediction_target_date + INTERVAL '1 day')
    ),
    CONSTRAINT valid_regime_brier CHECK (
        regime_brier_score IS NULL OR (regime_brier_score >= 0 AND regime_brier_score <= 2)
    )
);

CREATE INDEX IF NOT EXISTS idx_regime_beliefs_asset_date
ON fhq_governance.ex_ante_regime_beliefs(asset_id, prediction_target_date DESC);

CREATE INDEX IF NOT EXISTS idx_regime_beliefs_predicted
ON fhq_governance.ex_ante_regime_beliefs(predicted_regime, belief_formed_at DESC);

CREATE INDEX IF NOT EXISTS idx_regime_beliefs_unresolved
ON fhq_governance.ex_ante_regime_beliefs(outcome_observed_at)
WHERE outcome_observed_at IS NULL;

COMMENT ON TABLE fhq_governance.ex_ante_regime_beliefs IS
'CEO-DIR-2026-101: Ex-ante regime beliefs enabling Regime Brier Score.
Transforms regime from classification (label) to epistemic belief (testable forecast).
Every belief must be formed BEFORE the observation window it predicts.';


-- ============================================================================
-- SECTION 2: Epistemic Null Tracking Table
-- ============================================================================
-- CEO Mandate: "Absence of data must be explicitly classified as epistemic null"
-- "Learning systems improve fastest when they track why they did not learn"

CREATE TABLE IF NOT EXISTS fhq_governance.epistemic_null_log (
    null_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- What we tried to learn
    metric_type TEXT NOT NULL,
    asset_id TEXT NOT NULL,
    observation_date DATE NOT NULL,

    -- Why we could not learn
    null_reason TEXT NOT NULL,
    -- Valid reasons: NO_FORECAST, NO_OUTCOME, HORIZON_INCOMPLETE,
    --                DATA_QUALITY_FAIL, REGIME_UNDEFINED, NOT_APPLICABLE

    null_reason_detail TEXT,

    -- Context
    attempted_at TIMESTAMPTZ DEFAULT NOW(),
    attempted_by TEXT NOT NULL,

    -- Was this eventually resolved?
    resolved_at TIMESTAMPTZ,
    resolved_by TEXT,
    resolution_action TEXT,

    -- Audit
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT valid_null_reason CHECK (null_reason IN (
        'NO_FORECAST',
        'NO_OUTCOME',
        'HORIZON_INCOMPLETE',
        'DATA_QUALITY_FAIL',
        'REGIME_UNDEFINED',
        'MODEL_NOT_APPLICABLE',
        'ASSET_NOT_COVERED',
        'TEMPORAL_GAP'
    ))
);

CREATE INDEX IF NOT EXISTS idx_epistemic_null_reason
ON fhq_governance.epistemic_null_log(null_reason, observation_date DESC);

CREATE INDEX IF NOT EXISTS idx_epistemic_null_asset
ON fhq_governance.epistemic_null_log(asset_id, metric_type);

COMMENT ON TABLE fhq_governance.epistemic_null_log IS
'CEO-DIR-2026-101: Verified Ignorance tracking.
Tracks WHY the system did not learn, not just THAT it did not learn.
This enables second-order learning improvement.';


-- ============================================================================
-- SECTION 3: Regime Belief Formation Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.record_regime_belief(
    p_asset_id TEXT,
    p_regime_probabilities JSONB,
    p_prediction_target_date DATE,
    p_horizon_hours INTEGER DEFAULT 24,
    p_model_version TEXT DEFAULT NULL,
    p_generating_agent TEXT DEFAULT 'FINN'
)
RETURNS UUID AS $$
DECLARE
    v_belief_id UUID;
    v_predicted_regime TEXT;
    v_max_prob NUMERIC;
    v_entropy NUMERIC;
    v_evidence_hash TEXT;
    v_prob_sum NUMERIC;
BEGIN
    -- Validate probability distribution sums to ~1.0
    SELECT SUM(value::NUMERIC) INTO v_prob_sum
    FROM jsonb_each_text(p_regime_probabilities);

    IF v_prob_sum < 0.99 OR v_prob_sum > 1.01 THEN
        RAISE EXCEPTION 'Regime probabilities must sum to 1.0, got %', v_prob_sum;
    END IF;

    -- Find predicted regime (highest probability)
    SELECT key, value::NUMERIC INTO v_predicted_regime, v_max_prob
    FROM jsonb_each_text(p_regime_probabilities)
    ORDER BY value::NUMERIC DESC
    LIMIT 1;

    -- Calculate entropy: -Σ(p * log(p))
    SELECT -SUM(
        CASE WHEN value::NUMERIC > 0
        THEN value::NUMERIC * LN(value::NUMERIC)
        ELSE 0 END
    ) INTO v_entropy
    FROM jsonb_each_text(p_regime_probabilities);

    -- Generate evidence hash
    v_evidence_hash := 'sha256:' || encode(sha256(
        (p_asset_id || p_regime_probabilities::TEXT || p_prediction_target_date::TEXT || NOW()::TEXT)::bytea
    ), 'hex');

    INSERT INTO fhq_governance.ex_ante_regime_beliefs (
        asset_id,
        predicted_regime,
        regime_probabilities,
        prediction_horizon_hours,
        prediction_target_date,
        max_probability,
        entropy,
        model_version,
        generating_agent,
        evidence_hash
    ) VALUES (
        p_asset_id,
        v_predicted_regime,
        p_regime_probabilities,
        p_horizon_hours,
        p_prediction_target_date,
        v_max_prob,
        v_entropy,
        p_model_version,
        p_generating_agent,
        v_evidence_hash
    ) RETURNING belief_id INTO v_belief_id;

    RETURN v_belief_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_governance.record_regime_belief IS
'CEO-DIR-2026-101: Records an ex-ante regime belief with probability distribution.
The belief MUST be formed before the prediction target date.
Returns belief_id for later outcome resolution.';


-- ============================================================================
-- SECTION 4: Regime Belief Resolution Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.resolve_regime_belief(
    p_belief_id UUID,
    p_actual_regime TEXT
)
RETURNS JSONB AS $$
DECLARE
    v_belief RECORD;
    v_brier NUMERIC;
    v_prob_for_actual NUMERIC;
BEGIN
    -- Get the belief
    SELECT * INTO v_belief
    FROM fhq_governance.ex_ante_regime_beliefs
    WHERE belief_id = p_belief_id;

    IF v_belief IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'Belief not found');
    END IF;

    IF v_belief.outcome_observed_at IS NOT NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'Belief already resolved');
    END IF;

    -- Get probability assigned to actual regime
    v_prob_for_actual := COALESCE(
        (v_belief.regime_probabilities ->> p_actual_regime)::NUMERIC,
        0
    );

    -- Calculate Regime Brier Score
    -- Brier = Σ(forecast_prob - outcome_indicator)² over all regimes
    -- For multi-class: sum of squared differences where outcome_indicator = 1 for actual, 0 for others
    SELECT SUM(
        POWER(
            value::NUMERIC - CASE WHEN key = p_actual_regime THEN 1 ELSE 0 END,
            2
        )
    ) INTO v_brier
    FROM jsonb_each_text(v_belief.regime_probabilities);

    -- Update the belief with outcome
    UPDATE fhq_governance.ex_ante_regime_beliefs
    SET
        actual_regime = p_actual_regime,
        outcome_observed_at = NOW(),
        regime_brier_score = v_brier,
        belief_was_correct = (v_belief.predicted_regime = p_actual_regime),
        updated_at = NOW()
    WHERE belief_id = p_belief_id;

    RETURN jsonb_build_object(
        'success', true,
        'belief_id', p_belief_id,
        'predicted_regime', v_belief.predicted_regime,
        'actual_regime', p_actual_regime,
        'belief_was_correct', (v_belief.predicted_regime = p_actual_regime),
        'regime_brier_score', v_brier,
        'probability_for_actual', v_prob_for_actual,
        'max_probability', v_belief.max_probability
    );
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_governance.resolve_regime_belief IS
'CEO-DIR-2026-101: Resolves a regime belief with actual outcome.
Calculates Regime Brier Score for calibration analysis.';


-- ============================================================================
-- SECTION 5: Log Epistemic Null Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.log_epistemic_null(
    p_metric_type TEXT,
    p_asset_id TEXT,
    p_observation_date DATE,
    p_null_reason TEXT,
    p_reason_detail TEXT DEFAULT NULL,
    p_attempted_by TEXT DEFAULT 'STIG'
)
RETURNS UUID AS $$
DECLARE
    v_null_id UUID;
BEGIN
    INSERT INTO fhq_governance.epistemic_null_log (
        metric_type,
        asset_id,
        observation_date,
        null_reason,
        null_reason_detail,
        attempted_by
    ) VALUES (
        p_metric_type,
        p_asset_id,
        p_observation_date,
        p_null_reason,
        p_reason_detail,
        p_attempted_by
    ) RETURNING null_id INTO v_null_id;

    RETURN v_null_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_governance.log_epistemic_null IS
'CEO-DIR-2026-101: Logs verified ignorance - tracks WHY learning did not occur.';


-- ============================================================================
-- SECTION 6: Regime Belief Calibration View
-- ============================================================================

CREATE OR REPLACE VIEW fhq_governance.v_regime_belief_calibration AS
SELECT
    predicted_regime,
    COUNT(*) AS total_beliefs,
    COUNT(*) FILTER (WHERE belief_was_correct) AS correct_beliefs,
    ROUND(
        COUNT(*) FILTER (WHERE belief_was_correct)::NUMERIC / NULLIF(COUNT(*), 0) * 100,
        2
    ) AS hit_rate_pct,
    ROUND(AVG(regime_brier_score), 4) AS avg_regime_brier,
    ROUND(AVG(max_probability), 4) AS avg_confidence,
    ROUND(AVG(entropy), 4) AS avg_entropy,
    -- Calibration check: confidence should match hit rate
    ROUND(
        AVG(max_probability) - (COUNT(*) FILTER (WHERE belief_was_correct)::NUMERIC / NULLIF(COUNT(*), 0)),
        4
    ) AS overconfidence_score,
    MIN(belief_formed_at) AS first_belief,
    MAX(belief_formed_at) AS latest_belief
FROM fhq_governance.ex_ante_regime_beliefs
WHERE outcome_observed_at IS NOT NULL
GROUP BY predicted_regime
ORDER BY total_beliefs DESC;

COMMENT ON VIEW fhq_governance.v_regime_belief_calibration IS
'CEO-DIR-2026-101: Regime belief calibration analysis.
overconfidence_score > 0 means system is overconfident about that regime.';


-- ============================================================================
-- SECTION 7: Epistemic Null Summary View
-- ============================================================================

CREATE OR REPLACE VIEW fhq_governance.v_epistemic_null_summary AS
SELECT
    null_reason,
    metric_type,
    COUNT(*) AS null_count,
    COUNT(DISTINCT asset_id) AS assets_affected,
    MIN(observation_date) AS first_occurrence,
    MAX(observation_date) AS latest_occurrence,
    COUNT(*) FILTER (WHERE resolved_at IS NOT NULL) AS resolved_count,
    ROUND(
        COUNT(*) FILTER (WHERE resolved_at IS NOT NULL)::NUMERIC / NULLIF(COUNT(*), 0) * 100,
        2
    ) AS resolution_rate_pct
FROM fhq_governance.epistemic_null_log
GROUP BY null_reason, metric_type
ORDER BY null_count DESC;

COMMENT ON VIEW fhq_governance.v_epistemic_null_summary IS
'CEO-DIR-2026-101: Summary of verified ignorance by reason and metric type.
High counts indicate systematic learning gaps that need addressing.';


-- ============================================================================
-- SECTION 8: Regime Learning Velocity View
-- ============================================================================

CREATE OR REPLACE VIEW fhq_governance.v_regime_learning_velocity AS
WITH weekly_stats AS (
    SELECT
        DATE_TRUNC('week', belief_formed_at) AS week_start,
        predicted_regime,
        COUNT(*) AS beliefs,
        AVG(regime_brier_score) AS avg_brier,
        SUM(CASE WHEN belief_was_correct THEN 1 ELSE 0 END)::NUMERIC / NULLIF(COUNT(*), 0) AS hit_rate
    FROM fhq_governance.ex_ante_regime_beliefs
    WHERE outcome_observed_at IS NOT NULL
    GROUP BY DATE_TRUNC('week', belief_formed_at), predicted_regime
)
SELECT
    week_start,
    predicted_regime,
    beliefs,
    ROUND(avg_brier, 4) AS avg_brier,
    ROUND(hit_rate, 4) AS hit_rate,
    -- Week-over-week Brier improvement (negative = better)
    ROUND(
        avg_brier - LAG(avg_brier) OVER (PARTITION BY predicted_regime ORDER BY week_start),
        4
    ) AS brier_delta_wow,
    -- Week-over-week hit rate improvement (positive = better)
    ROUND(
        hit_rate - LAG(hit_rate) OVER (PARTITION BY predicted_regime ORDER BY week_start),
        4
    ) AS hit_rate_delta_wow
FROM weekly_stats
ORDER BY week_start DESC, predicted_regime;

COMMENT ON VIEW fhq_governance.v_regime_learning_velocity IS
'CEO-DIR-2026-101: Regime-specific learning velocity tracking.
brier_delta_wow < 0 indicates improving regime prediction.';


-- ============================================================================
-- SECTION 9: Register Migration
-- ============================================================================

INSERT INTO fhq_governance.governance_actions_log (
    action_type,
    action_target,
    action_target_type,
    initiated_by,
    decision,
    decision_rationale,
    metadata,
    signature,
    agent_id
) VALUES (
    'MIGRATION',
    'CEO-DIR-2026-101',
    'EPISTEMIC_FRAMEWORK',
    'STIG',
    'APPROVED',
    'Migration 275: Ex-ante regime beliefs - Transforms regime from classification to epistemic belief',
    jsonb_build_object(
        'migration', '275_ex_ante_regime_beliefs.sql',
        'phase', 'C_PREREQUISITE',
        'gaps_addressed', ARRAY['GAP-REGIME-001', 'GAP-IGNORANCE-001'],
        'objects_created', ARRAY[
            'fhq_governance.ex_ante_regime_beliefs',
            'fhq_governance.epistemic_null_log',
            'fhq_governance.record_regime_belief()',
            'fhq_governance.resolve_regime_belief()',
            'fhq_governance.log_epistemic_null()',
            'fhq_governance.v_regime_belief_calibration',
            'fhq_governance.v_epistemic_null_summary',
            'fhq_governance.v_regime_learning_velocity'
        ],
        'ceo_mandate', 'Regime must become a forecastable belief, not just a state',
        'enables', ARRAY[
            'Regime Brier Score',
            'Regime-specific LVI',
            'Regime hallucination detection',
            'Verified ignorance tracking'
        ]
    ),
    'Ed25519:STIG_MIGRATION_275',
    'STIG'
);

COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================
-- Test regime belief recording:
-- SELECT fhq_governance.record_regime_belief(
--     'BTC-USD',
--     '{"BULL": 0.15, "BEAR": 0.10, "NEUTRAL": 0.20, "STRESS": 0.55}'::jsonb,
--     '2026-01-20',
--     24,
--     'FINN_HMM_v3'
-- );
--
-- Test epistemic null logging:
-- SELECT fhq_governance.log_epistemic_null(
--     'BRIER_SCORE',
--     'GLD',
--     '2026-01-19',
--     'NO_FORECAST',
--     'Asset not covered by FINN regime model'
-- );
--
-- View calibration:
-- SELECT * FROM fhq_governance.v_regime_belief_calibration;
-- SELECT * FROM fhq_governance.v_epistemic_null_summary;
