-- ============================================================================
-- Migration 276: Brier Score Decomposition (Epistemic Upgrade)
-- CEO-DIR-2026-101 Phase C Prerequisite - GAP-CALIBRATION-001 Remediation
-- ============================================================================
-- Purpose: Decompose Brier Score into Reliability, Resolution, Uncertainty
--          "You know how wrong you are, but not how you are wrong"
--
-- CEO Mandate: "Brier must be decomposed into:
--              - Reliability (calibration)
--              - Resolution
--              - Uncertainty
--              Without this, you know how wrong you are, but not HOW you are wrong."
--
-- Brier Decomposition Formula:
--   Brier = Reliability - Resolution + Uncertainty
--
-- Where:
--   Reliability = (1/N) * Σ n_k * (f_k - o_k)²  [calibration error, lower = better]
--   Resolution  = (1/N) * Σ n_k * (o_k - o_bar)² [discrimination ability, higher = better]
--   Uncertainty = o_bar * (1 - o_bar)           [inherent unpredictability]
--
-- Constitutional Alignment: ADR-017, ADR-019, ADR-020
-- VEGA Gate: G3 Required
-- Generated By: STIG (EC-003_2026_PRODUCTION)
-- Generated At: 2026-01-19
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECTION 1: Brier Decomposition Results Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS fhq_governance.brier_decomposition (
    decomposition_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Scope
    asset_id TEXT,  -- NULL for system-wide
    forecast_type TEXT NOT NULL DEFAULT 'PRICE_DIRECTION',
    regime TEXT,    -- NULL for all regimes

    -- Period
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    sample_size INTEGER NOT NULL,

    -- Raw Brier
    brier_score NUMERIC NOT NULL,

    -- Decomposition Components
    reliability NUMERIC NOT NULL,     -- Calibration error (lower = better)
    resolution NUMERIC NOT NULL,      -- Discrimination ability (higher = better)
    uncertainty NUMERIC NOT NULL,     -- Inherent unpredictability (fixed for period)

    -- Derived Metrics
    reliability_skill NUMERIC GENERATED ALWAYS AS (
        CASE WHEN uncertainty > 0 THEN 1 - (reliability / uncertainty) ELSE NULL END
    ) STORED,  -- How much calibration error relative to inherent uncertainty

    resolution_skill NUMERIC GENERATED ALWAYS AS (
        CASE WHEN uncertainty > 0 THEN resolution / uncertainty ELSE NULL END
    ) STORED,  -- How much discrimination relative to inherent uncertainty

    brier_skill_score NUMERIC GENERATED ALWAYS AS (
        CASE WHEN uncertainty > 0 THEN (resolution - reliability) / uncertainty ELSE NULL END
    ) STORED,  -- Overall skill (BSS), positive = better than base rate

    -- Calibration diagnosis
    is_overconfident BOOLEAN GENERATED ALWAYS AS (reliability > 0.05) STORED,
    is_well_calibrated BOOLEAN GENERATED ALWAYS AS (reliability < 0.02) STORED,
    has_resolution BOOLEAN GENERATED ALWAYS AS (resolution > 0.01) STORED,

    -- Metadata
    computed_at TIMESTAMPTZ DEFAULT NOW(),
    computed_by TEXT DEFAULT 'STIG',
    evidence_hash TEXT NOT NULL,

    -- Constraints
    CONSTRAINT valid_brier CHECK (brier_score >= 0 AND brier_score <= 1),
    CONSTRAINT valid_reliability CHECK (reliability >= 0),
    CONSTRAINT valid_resolution CHECK (resolution >= 0),
    CONSTRAINT valid_uncertainty CHECK (uncertainty >= 0 AND uncertainty <= 0.25),
    CONSTRAINT valid_decomposition CHECK (
        ABS(brier_score - (reliability - resolution + uncertainty)) < 0.001
    )
);

CREATE INDEX IF NOT EXISTS idx_brier_decomposition_asset
ON fhq_governance.brier_decomposition(asset_id, period_end DESC);

CREATE INDEX IF NOT EXISTS idx_brier_decomposition_regime
ON fhq_governance.brier_decomposition(regime, period_end DESC) WHERE regime IS NOT NULL;

COMMENT ON TABLE fhq_governance.brier_decomposition IS
'CEO-DIR-2026-101: Brier score decomposition into Reliability, Resolution, Uncertainty.
Enables diagnosis of HOW the system is wrong, not just THAT it is wrong.';


-- ============================================================================
-- SECTION 2: Brier Decomposition Computation Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.compute_brier_decomposition(
    p_asset_id TEXT DEFAULT NULL,
    p_start_date DATE DEFAULT NULL,
    p_end_date DATE DEFAULT NULL,
    p_regime TEXT DEFAULT NULL,
    p_forecast_type TEXT DEFAULT 'PRICE_DIRECTION'
)
RETURNS TABLE (
    asset_id TEXT,
    forecast_type TEXT,
    regime TEXT,
    period_start DATE,
    period_end DATE,
    sample_size INTEGER,
    brier_score NUMERIC,
    reliability NUMERIC,
    resolution NUMERIC,
    uncertainty NUMERIC,
    evidence_hash TEXT
) AS $$
DECLARE
    v_start DATE := COALESCE(p_start_date, CURRENT_DATE - INTERVAL '30 days');
    v_end DATE := COALESCE(p_end_date, CURRENT_DATE);
BEGIN
    RETURN QUERY
    WITH base_data AS (
        -- Get all forecasts with outcomes
        SELECT
            bsl.asset_id,
            bsl.forecast_probability AS forecast,
            CASE WHEN bsl.actual_outcome THEN 1.0 ELSE 0.0 END AS outcome,
            bsl.regime
        FROM fhq_governance.brier_score_ledger bsl
        WHERE (p_asset_id IS NULL OR bsl.asset_id = p_asset_id)
          AND (p_regime IS NULL OR bsl.regime = p_regime)
          AND bsl.forecast_type = p_forecast_type
          AND bsl.forecast_timestamp::DATE BETWEEN v_start AND v_end
          AND bsl.forecast_probability IS NOT NULL
          AND bsl.actual_outcome IS NOT NULL
    ),
    binned AS (
        -- Bin forecasts into 10 bins for decomposition
        SELECT
            bd.asset_id,
            FLOOR(bd.forecast * 10) / 10 AS bin_lower,
            bd.forecast,
            bd.outcome
        FROM base_data bd
    ),
    bin_stats AS (
        -- Calculate statistics per bin
        SELECT
            b.asset_id,
            b.bin_lower,
            COUNT(*) AS n_k,
            AVG(b.forecast) AS f_k,  -- Mean forecast in bin
            AVG(b.outcome) AS o_k    -- Observed frequency in bin
        FROM binned b
        GROUP BY b.asset_id, b.bin_lower
    ),
    overall_stats AS (
        -- Calculate overall base rate
        SELECT
            bd.asset_id,
            COUNT(*) AS N,
            AVG(bd.outcome) AS o_bar  -- Overall base rate
        FROM base_data bd
        GROUP BY bd.asset_id
    ),
    decomposition AS (
        SELECT
            os.asset_id,
            os.N,
            os.o_bar,

            -- Brier Score: (1/N) * Σ (forecast - outcome)²
            (SELECT AVG(POWER(forecast - outcome, 2)) FROM base_data WHERE base_data.asset_id = os.asset_id)
                AS brier,

            -- Reliability: (1/N) * Σ n_k * (f_k - o_k)²
            (SELECT SUM(bs.n_k * POWER(bs.f_k - bs.o_k, 2)) / os.N
             FROM bin_stats bs WHERE bs.asset_id = os.asset_id)
                AS rel,

            -- Resolution: (1/N) * Σ n_k * (o_k - o_bar)²
            (SELECT SUM(bs.n_k * POWER(bs.o_k - os.o_bar, 2)) / os.N
             FROM bin_stats bs WHERE bs.asset_id = os.asset_id)
                AS res,

            -- Uncertainty: o_bar * (1 - o_bar)
            os.o_bar * (1 - os.o_bar) AS unc

        FROM overall_stats os
        WHERE os.N >= 10  -- Minimum sample size for meaningful decomposition
    )
    SELECT
        d.asset_id,
        p_forecast_type,
        p_regime,
        v_start,
        v_end,
        d.N::INTEGER,
        ROUND(d.brier, 6)::NUMERIC,
        ROUND(d.rel, 6)::NUMERIC,
        ROUND(d.res, 6)::NUMERIC,
        ROUND(d.unc, 6)::NUMERIC,
        ('sha256:' || encode(sha256(
            (COALESCE(d.asset_id, 'SYSTEM') || d.brier::TEXT || d.rel::TEXT || d.res::TEXT || v_start::TEXT || v_end::TEXT)::bytea
        ), 'hex'))::TEXT
    FROM decomposition d
    WHERE d.brier IS NOT NULL;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fhq_governance.compute_brier_decomposition IS
'CEO-DIR-2026-101: Computes Brier decomposition (Reliability, Resolution, Uncertainty).
Reliability = calibration error (lower = better)
Resolution = discrimination ability (higher = better)
Uncertainty = inherent unpredictability (fixed for period)
Brier = Reliability - Resolution + Uncertainty';


-- ============================================================================
-- SECTION 3: Populate Brier Decomposition Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.populate_brier_decomposition(
    p_start_date DATE DEFAULT NULL,
    p_end_date DATE DEFAULT NULL
)
RETURNS INTEGER AS $$
DECLARE
    v_inserted INTEGER := 0;
    v_record RECORD;
BEGIN
    FOR v_record IN
        SELECT * FROM fhq_governance.compute_brier_decomposition(
            p_start_date := p_start_date,
            p_end_date := p_end_date
        )
    LOOP
        INSERT INTO fhq_governance.brier_decomposition (
            asset_id,
            forecast_type,
            regime,
            period_start,
            period_end,
            sample_size,
            brier_score,
            reliability,
            resolution,
            uncertainty,
            evidence_hash
        ) VALUES (
            v_record.asset_id,
            v_record.forecast_type,
            v_record.regime,
            v_record.period_start,
            v_record.period_end,
            v_record.sample_size,
            v_record.brier_score,
            v_record.reliability,
            v_record.resolution,
            v_record.uncertainty,
            v_record.evidence_hash
        );
        v_inserted := v_inserted + 1;
    END LOOP;

    RETURN v_inserted;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_governance.populate_brier_decomposition IS
'CEO-DIR-2026-101: Populates brier_decomposition table for all assets';


-- ============================================================================
-- SECTION 4: Calibration Diagnosis View
-- ============================================================================

CREATE OR REPLACE VIEW fhq_governance.v_calibration_diagnosis AS
SELECT
    bd.asset_id,
    bd.forecast_type,
    bd.period_start,
    bd.period_end,
    bd.sample_size,

    -- Raw scores
    bd.brier_score,
    bd.reliability,
    bd.resolution,
    bd.uncertainty,

    -- Skill scores
    bd.brier_skill_score,
    bd.reliability_skill,
    bd.resolution_skill,

    -- Diagnosis
    bd.is_overconfident,
    bd.is_well_calibrated,
    bd.has_resolution,

    -- Actionable diagnosis
    CASE
        WHEN bd.reliability > 0.05 AND bd.resolution < 0.01 THEN
            'CRITICAL: Overconfident AND no discrimination - reduce confidence, improve model'
        WHEN bd.reliability > 0.05 THEN
            'WARNING: Overconfident - apply SkillDamper, recalibrate'
        WHEN bd.resolution < 0.01 THEN
            'WARNING: No discrimination - model cannot distinguish outcomes'
        WHEN bd.reliability < 0.02 AND bd.resolution > 0.02 THEN
            'GOOD: Well-calibrated with discrimination'
        ELSE
            'ACCEPTABLE: Minor calibration issues'
    END AS diagnosis,

    -- Recommended action
    CASE
        WHEN bd.reliability > 0.05 THEN
            'Apply confidence ceiling: ' || ROUND(GREATEST(0.3, 1 - bd.reliability * 2), 2)::TEXT
        WHEN bd.resolution < 0.01 THEN
            'Review feature set - current features not predictive'
        ELSE
            'No immediate action required'
    END AS recommended_action,

    bd.computed_at

FROM fhq_governance.brier_decomposition bd
WHERE bd.computed_at = (
    SELECT MAX(computed_at)
    FROM fhq_governance.brier_decomposition
    WHERE asset_id IS NOT DISTINCT FROM bd.asset_id
      AND forecast_type = bd.forecast_type
)
ORDER BY bd.reliability DESC;

COMMENT ON VIEW fhq_governance.v_calibration_diagnosis IS
'CEO-DIR-2026-101: Actionable calibration diagnosis based on Brier decomposition.
Provides specific recommendations for SkillDamper and model improvement.';


-- ============================================================================
-- SECTION 5: SkillDamper Integration View
-- ============================================================================

CREATE OR REPLACE VIEW fhq_governance.v_skilldamper_inputs AS
SELECT
    bd.asset_id,
    bd.brier_score,
    bd.reliability AS calibration_error,
    bd.brier_skill_score AS skill_score,

    -- Compute recommended damping factor based on miscalibration
    CASE
        WHEN bd.reliability > 0.10 THEN 0.50  -- Severe miscalibration: halve confidence
        WHEN bd.reliability > 0.05 THEN 0.70  -- Moderate miscalibration: 30% reduction
        WHEN bd.reliability > 0.02 THEN 0.85  -- Minor miscalibration: 15% reduction
        ELSE 1.00  -- Well-calibrated: no damping
    END AS recommended_damping_factor,

    -- Confidence ceiling based on decomposition
    GREATEST(0.40, LEAST(0.90, 1 - bd.reliability * 3)) AS recommended_confidence_ceiling,

    bd.computed_at,
    bd.evidence_hash

FROM fhq_governance.brier_decomposition bd
WHERE bd.computed_at = (
    SELECT MAX(computed_at)
    FROM fhq_governance.brier_decomposition
    WHERE asset_id IS NOT DISTINCT FROM bd.asset_id
);

COMMENT ON VIEW fhq_governance.v_skilldamper_inputs IS
'CEO-DIR-2026-101: SkillDamper input parameters derived from Brier decomposition.
Enables automatic confidence adjustment based on calibration error.';


-- ============================================================================
-- SECTION 6: System Calibration Summary
-- ============================================================================

CREATE OR REPLACE VIEW fhq_governance.v_system_calibration_health AS
SELECT
    COUNT(DISTINCT asset_id) AS assets_analyzed,
    AVG(brier_score) AS avg_brier,
    AVG(reliability) AS avg_reliability,
    AVG(resolution) AS avg_resolution,
    AVG(uncertainty) AS avg_uncertainty,
    AVG(brier_skill_score) AS avg_skill_score,

    -- System-wide diagnosis
    COUNT(*) FILTER (WHERE is_overconfident) AS overconfident_assets,
    COUNT(*) FILTER (WHERE is_well_calibrated) AS well_calibrated_assets,
    COUNT(*) FILTER (WHERE has_resolution) AS discriminating_assets,

    -- Overall health score (0-100)
    ROUND(
        (1 - COALESCE(AVG(reliability), 0.25) / 0.25) * 50 +  -- Calibration component (50 pts)
        COALESCE(AVG(resolution), 0) / 0.1 * 50               -- Resolution component (50 pts)
    , 2) AS calibration_health_score,

    MAX(computed_at) AS latest_computation

FROM fhq_governance.brier_decomposition
WHERE computed_at >= NOW() - INTERVAL '7 days';

COMMENT ON VIEW fhq_governance.v_system_calibration_health IS
'CEO-DIR-2026-101: System-wide calibration health summary.
calibration_health_score: 0-100, higher = better calibrated system.';


-- ============================================================================
-- SECTION 7: Register Migration
-- ============================================================================

INSERT INTO fhq_governance.governance_actions_log (
    action_type,
    action_target,
    action_target_type,
    initiated_by,
    decision,
    decision_rationale,
    metadata,
    signature,
    agent_id
) VALUES (
    'MIGRATION',
    'CEO-DIR-2026-101',
    'EPISTEMIC_FRAMEWORK',
    'STIG',
    'APPROVED',
    'Migration 276: Brier decomposition - Enables diagnosis of HOW system is wrong',
    jsonb_build_object(
        'migration', '276_brier_decomposition.sql',
        'phase', 'C_PREREQUISITE',
        'gap_addressed', 'GAP-CALIBRATION-001',
        'objects_created', ARRAY[
            'fhq_governance.brier_decomposition',
            'fhq_governance.compute_brier_decomposition()',
            'fhq_governance.populate_brier_decomposition()',
            'fhq_governance.v_calibration_diagnosis',
            'fhq_governance.v_skilldamper_inputs',
            'fhq_governance.v_system_calibration_health'
        ],
        'ceo_mandate', 'Know HOW you are wrong, not just THAT you are wrong',
        'decomposition_formula', 'Brier = Reliability - Resolution + Uncertainty',
        'enables', ARRAY[
            'Automatic SkillDamper parameter tuning',
            'Calibration-based confidence ceilings',
            'Second-order learning improvement'
        ]
    ),
    'Ed25519:STIG_MIGRATION_276',
    'STIG'
);

COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================
-- Compute decomposition:
-- SELECT fhq_governance.populate_brier_decomposition('2026-01-01', '2026-01-19');
--
-- View decomposition results:
-- SELECT * FROM fhq_governance.compute_brier_decomposition('BTC-USD', '2026-01-01', '2026-01-19');
--
-- View diagnosis:
-- SELECT * FROM fhq_governance.v_calibration_diagnosis;
--
-- View SkillDamper inputs:
-- SELECT * FROM fhq_governance.v_skilldamper_inputs;
--
-- View system health:
-- SELECT * FROM fhq_governance.v_system_calibration_health;
