-- ============================================================================
-- Migration 277: Hindsight Firewall (CEO-DIR-2026-105)
-- Retrospective Epistemic Calibration & Hindsight Boundary
-- ============================================================================
-- Purpose: Ensure retrospective analysis cannot contaminate ex-ante beliefs
--
-- CEO Mandate: "All dekomponering utført retrospektivt skal klassifiseres som
--              Diagnostic-Only. Det skal aldri tolkes som hva systemet 'visste'
--              på prediksjonstidspunktet, men som en post-hoc disseksjon av
--              systemets ferdighetsstruktur."
--
-- Key Constraints:
--   1. is_retrospective = TRUE flag for all backfilled data
--   2. Non-Eligibility Clause enforcement
--   3. VEGA cryptographic verification of non-contamination
--
-- CEO Improvements Applied:
--   A. Non-Eligibility Clause (explicit negative rights)
--   B. VEGA as "bevisvokter" (evidence guardian), not just "kontroll"
--   C. Learning Hypothesis tracking (non-executable)
--
-- Constitutional Alignment: ADR-002, ADR-004, ADR-013, ADR-014
-- VEGA Gate: G3 Required
-- Generated By: STIG (EC-003_2026_PRODUCTION)
-- Generated At: 2026-01-19
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECTION 1: Add Hindsight Firewall Column to brier_decomposition
-- ============================================================================

-- Add is_retrospective flag
ALTER TABLE fhq_governance.brier_decomposition
ADD COLUMN IF NOT EXISTS is_retrospective BOOLEAN DEFAULT FALSE;

-- Add retrospective computation timestamp (when the analysis was done, not the period)
ALTER TABLE fhq_governance.brier_decomposition
ADD COLUMN IF NOT EXISTS retrospective_computed_at TIMESTAMPTZ;

-- Add cohort binding columns for Rule 1
ALTER TABLE fhq_governance.brier_decomposition
ADD COLUMN IF NOT EXISTS asset_class TEXT;

ALTER TABLE fhq_governance.brier_decomposition
ADD COLUMN IF NOT EXISTS horizon TEXT DEFAULT 'T+1';

COMMENT ON COLUMN fhq_governance.brier_decomposition.is_retrospective IS
'CEO-DIR-2026-105: TRUE if computed retrospectively. Diagnostic-Only, NOT ex-ante belief.
Non-Eligibility Clause applies: cannot be used for model selection, parameter adjustment,
retraining, or decision damping/amplification until 2 learning cycles post-computation.';

COMMENT ON COLUMN fhq_governance.brier_decomposition.retrospective_computed_at IS
'Timestamp when retrospective analysis was performed (hindsight moment)';

-- Create index for retrospective queries
CREATE INDEX IF NOT EXISTS idx_brier_decomposition_retrospective
ON fhq_governance.brier_decomposition(is_retrospective, computed_at);

CREATE INDEX IF NOT EXISTS idx_brier_decomposition_cohort
ON fhq_governance.brier_decomposition(asset_class, forecast_type, horizon);


-- ============================================================================
-- SECTION 2: Non-Eligibility Clause Tracking Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS fhq_governance.retrospective_non_eligibility_log (
    log_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Source reference
    decomposition_id UUID NOT NULL REFERENCES fhq_governance.brier_decomposition(decomposition_id),

    -- Non-eligibility period
    computed_at TIMESTAMPTZ NOT NULL,
    eligibility_date DATE NOT NULL,  -- Date when this becomes eligible for use

    -- Prohibited uses (CEO Improvement A)
    prohibited_uses JSONB NOT NULL DEFAULT '["model_selection", "parameter_adjustment", "retraining", "decision_damping"]'::jsonb,

    -- Status tracking
    is_eligible BOOLEAN DEFAULT FALSE,
    eligibility_verified_at TIMESTAMPTZ,
    eligibility_verified_by TEXT,

    -- Learning cycles tracking (minimum 2 required)
    learning_cycles_required INTEGER DEFAULT 2,
    learning_cycles_completed INTEGER DEFAULT 0,

    -- Violation tracking
    violation_attempted BOOLEAN DEFAULT FALSE,
    violation_details JSONB,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_non_eligibility_decomposition
ON fhq_governance.retrospective_non_eligibility_log(decomposition_id);

CREATE INDEX IF NOT EXISTS idx_non_eligibility_eligible
ON fhq_governance.retrospective_non_eligibility_log(eligibility_date, is_eligible);

COMMENT ON TABLE fhq_governance.retrospective_non_eligibility_log IS
'CEO-DIR-2026-105 Section 2.1: Non-Eligibility Clause enforcement.
Retrospective decompositions are explicitly NOT allowed for:
a) model selection  b) parameter adjustment  c) retraining  d) decision damping/amplification
until minimum 2 learning cycles have completed post-computation.';


-- ============================================================================
-- SECTION 3: VEGA Evidence Guardian Table (CEO Improvement B)
-- ============================================================================

CREATE TABLE IF NOT EXISTS fhq_governance.hindsight_contamination_audit (
    audit_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Audit scope
    audit_date DATE NOT NULL DEFAULT CURRENT_DATE,
    audit_type TEXT NOT NULL DEFAULT 'CONTAMINATION_CHECK',

    -- Tables scanned
    tables_scanned JSONB NOT NULL,  -- List of tables checked for contamination

    -- Results
    contamination_found BOOLEAN NOT NULL,
    contaminated_references JSONB,  -- Details of any contamination found

    -- Hash lineage verification
    hash_lineage_verified BOOLEAN NOT NULL,
    dependency_scan_result JSONB,

    -- VEGA attestation
    attested_by TEXT DEFAULT 'VEGA',
    attestation_signature TEXT,
    attestation_timestamp TIMESTAMPTZ DEFAULT NOW(),

    -- Evidence chain
    evidence_hash TEXT NOT NULL,

    CONSTRAINT valid_audit_type CHECK (audit_type IN ('CONTAMINATION_CHECK', 'DEPENDENCY_SCAN', 'FULL_AUDIT'))
);

CREATE INDEX IF NOT EXISTS idx_contamination_audit_date
ON fhq_governance.hindsight_contamination_audit(audit_date DESC);

COMMENT ON TABLE fhq_governance.hindsight_contamination_audit IS
'CEO-DIR-2026-105 CEO Improvement B: VEGA as evidence guardian, not just attestor.
VEGA cryptographically verifies that no rows with is_retrospective = TRUE
have been referenced in ex_ante_regime_beliefs, SkillDamper input-views, or decision_plan artifacts.';


-- ============================================================================
-- SECTION 4: Learning Hypothesis Registry (CEO Improvement C)
-- ============================================================================

CREATE TABLE IF NOT EXISTS fhq_governance.learning_hypothesis_registry (
    hypothesis_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Hypothesis definition
    hypothesis_name TEXT NOT NULL,
    hypothesis_description TEXT NOT NULL,

    -- Expected manifestations (non-executable)
    expected_manifestations JSONB NOT NULL,

    -- Evaluation criteria
    evaluation_metrics JSONB NOT NULL,

    -- Status
    is_active BOOLEAN DEFAULT TRUE,
    is_executable BOOLEAN DEFAULT FALSE,  -- MUST be FALSE per CEO directive

    -- Tracking
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by TEXT DEFAULT 'STIG',

    CONSTRAINT non_executable_hypothesis CHECK (is_executable = FALSE)
);

-- Insert CEO's learning hypothesis (Non-Executable)
INSERT INTO fhq_governance.learning_hypothesis_registry (
    hypothesis_name,
    hypothesis_description,
    expected_manifestations,
    evaluation_metrics,
    is_active,
    is_executable
) VALUES (
    'CEO-DIR-2026-105 Learning Hypothesis',
    'FjordHQ antar som arbeidshypotese at forbedring i epistemisk ytelse primært vil manifestere seg som beskrevet i expected_manifestations. Denne hypotesen er IKKE handlingsutløsende, men brukes som evalueringsramme for fremtidige læringssykluser.',
    jsonb_build_object(
        'primary_manifestation_1', 'Økt Resolution FØR forbedret Reliability',
        'primary_manifestation_2', 'Reduksjon i EPISTEMIC_NULL med årsak REGIME_UNDEFINED',
        'primary_manifestation_3', 'Regime-spesifikk kalibreringskonvergens'
    ),
    jsonb_build_object(
        'resolution_improvement_rate', 'Monitor v_calibration_diagnosis.resolution over time',
        'epistemic_null_reduction', 'Monitor v_epistemic_null_summary by reason_code',
        'regime_calibration_variance', 'Monitor v_regime_belief_calibration spread by regime'
    ),
    TRUE,
    FALSE  -- CRITICAL: Must remain FALSE
);

COMMENT ON TABLE fhq_governance.learning_hypothesis_registry IS
'CEO-DIR-2026-105 CEO Improvement C: Learning hypothesis tracking.
Hypotheses define what kind of learning is expected WITHOUT baking it into the system.
is_executable MUST always be FALSE - these are evaluation frameworks, not action triggers.';


-- ============================================================================
-- SECTION 5: Update v_skilldamper_inputs to Respect Hindsight Firewall
-- ============================================================================

DROP VIEW IF EXISTS fhq_governance.v_skilldamper_inputs;
CREATE VIEW fhq_governance.v_skilldamper_inputs AS
SELECT
    bd.asset_id,
    bd.brier_score,
    bd.reliability AS calibration_error,
    bd.brier_skill_score AS skill_score,

    -- Compute recommended damping factor based on miscalibration
    CASE
        WHEN bd.reliability > 0.10 THEN 0.50  -- Severe miscalibration: halve confidence
        WHEN bd.reliability > 0.05 THEN 0.70  -- Moderate miscalibration: 30% reduction
        WHEN bd.reliability > 0.02 THEN 0.85  -- Minor miscalibration: 15% reduction
        ELSE 1.00  -- Well-calibrated: no damping
    END AS recommended_damping_factor,

    -- Confidence ceiling based on decomposition
    GREATEST(0.40, LEAST(0.90, 1 - bd.reliability * 3)) AS recommended_confidence_ceiling,

    -- Hindsight firewall warning
    bd.is_retrospective,
    CASE
        WHEN bd.is_retrospective THEN 'DIAGNOSTIC_ONLY: Cannot use for damping until 2 learning cycles complete'
        ELSE 'PROSPECTIVE: Can use for damping'
    END AS usage_status,

    bd.computed_at,
    bd.evidence_hash

FROM fhq_governance.brier_decomposition bd
WHERE bd.computed_at = (
    SELECT MAX(computed_at)
    FROM fhq_governance.brier_decomposition
    WHERE asset_id IS NOT DISTINCT FROM bd.asset_id
)
-- HINDSIGHT FIREWALL: Only show non-retrospective by default
-- Retrospective data requires explicit query
AND (bd.is_retrospective = FALSE OR bd.is_retrospective IS NULL);

COMMENT ON VIEW fhq_governance.v_skilldamper_inputs IS
'CEO-DIR-2026-105: SkillDamper input parameters with Hindsight Firewall.
By default excludes is_retrospective = TRUE data to prevent hindsight contamination.';


-- ============================================================================
-- SECTION 6: Diagnostic-Only View (Allows Retrospective)
-- ============================================================================

CREATE OR REPLACE VIEW fhq_governance.v_calibration_diagnosis_diagnostic AS
SELECT
    bd.asset_id,
    bd.asset_class,
    bd.forecast_type,
    bd.horizon,
    bd.period_start,
    bd.period_end,
    bd.sample_size,

    -- Raw scores
    bd.brier_score,
    bd.reliability,
    bd.resolution,
    bd.uncertainty,

    -- Skill scores
    bd.brier_skill_score,
    bd.reliability_skill,
    bd.resolution_skill,

    -- Diagnosis
    bd.is_overconfident,
    bd.is_well_calibrated,
    bd.has_resolution,

    -- Hindsight classification
    bd.is_retrospective,
    CASE
        WHEN bd.is_retrospective THEN 'POST-HOC DISSEKSJON'
        ELSE 'PROSPEKTIV'
    END AS analysis_type,

    -- Actionable diagnosis
    CASE
        WHEN bd.reliability > 0.05 AND bd.resolution < 0.01 THEN
            'CRITICAL: Overconfident AND no discrimination - reduce confidence, improve model'
        WHEN bd.reliability > 0.05 THEN
            'WARNING: Overconfident - apply SkillDamper, recalibrate'
        WHEN bd.resolution < 0.01 THEN
            'WARNING: No discrimination - model cannot distinguish outcomes'
        WHEN bd.reliability < 0.02 AND bd.resolution > 0.02 THEN
            'GOOD: Well-calibrated with discrimination'
        ELSE
            'ACCEPTABLE: Minor calibration issues'
    END AS diagnosis,

    -- Cohort information (Rule 1: Cohort-binding)
    'COHORT: ' || COALESCE(bd.asset_class, 'ALL') || ' / ' ||
    bd.forecast_type || ' / ' ||
    COALESCE(bd.horizon, 'T+1') AS cohort_binding,

    bd.computed_at,
    bd.retrospective_computed_at

FROM fhq_governance.brier_decomposition bd
ORDER BY bd.is_retrospective, bd.reliability DESC;

COMMENT ON VIEW fhq_governance.v_calibration_diagnosis_diagnostic IS
'CEO-DIR-2026-105: Diagnostic view that INCLUDES retrospective data.
For analysis purposes only. Data marked is_retrospective = TRUE is post-hoc disseksjon,
NOT what the system knew at prediction time. Non-Eligibility Clause applies.';


-- ============================================================================
-- SECTION 7: VEGA Contamination Check Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.check_hindsight_contamination()
RETURNS TABLE (
    check_name TEXT,
    is_contaminated BOOLEAN,
    contaminated_count INTEGER,
    details TEXT
) AS $$
BEGIN
    -- Check 1: ex_ante_regime_beliefs references
    RETURN QUERY
    SELECT
        'ex_ante_regime_beliefs'::TEXT,
        EXISTS(
            SELECT 1 FROM fhq_governance.ex_ante_regime_beliefs earb
            JOIN fhq_governance.brier_decomposition bd
                ON earb.created_at > bd.retrospective_computed_at
            WHERE bd.is_retrospective = TRUE
              AND earb.created_at > bd.computed_at
        )::BOOLEAN,
        0::INTEGER,
        'Checks if retrospective data influenced ex-ante beliefs'::TEXT;

    -- Check 2: SkillDamper direct references (via governance_actions_log)
    RETURN QUERY
    SELECT
        'skilldamper_actions'::TEXT,
        EXISTS(
            SELECT 1 FROM fhq_governance.governance_actions_log gal
            WHERE gal.action_type = 'SKILLDAMPER_ADJUSTMENT'
              AND gal.metadata->>'source' LIKE '%retrospective%'
        )::BOOLEAN,
        0::INTEGER,
        'Checks if retrospective data was used for SkillDamper'::TEXT;

    -- Check 3: decision_plan artifacts
    RETURN QUERY
    SELECT
        'decision_plans'::TEXT,
        FALSE::BOOLEAN,  -- No decision_plan table exists yet
        0::INTEGER,
        'No decision_plan artifacts exist - N/A'::TEXT;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fhq_governance.check_hindsight_contamination IS
'CEO-DIR-2026-105 CEO Improvement B: VEGA contamination verification function.
Checks that no retrospective data has contaminated ex-ante beliefs or SkillDamper inputs.';


-- ============================================================================
-- SECTION 8: Non-Eligibility Enforcement Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.register_retrospective_decomposition(
    p_decomposition_id UUID
)
RETURNS UUID AS $$
DECLARE
    v_log_id UUID;
    v_computed_at TIMESTAMPTZ;
BEGIN
    -- Get computation timestamp
    SELECT computed_at INTO v_computed_at
    FROM fhq_governance.brier_decomposition
    WHERE decomposition_id = p_decomposition_id;

    -- Calculate eligibility date (2 learning cycles = approx 14 days minimum)
    INSERT INTO fhq_governance.retrospective_non_eligibility_log (
        decomposition_id,
        computed_at,
        eligibility_date,
        prohibited_uses,
        learning_cycles_required,
        learning_cycles_completed
    ) VALUES (
        p_decomposition_id,
        v_computed_at,
        (v_computed_at + INTERVAL '14 days')::DATE,
        '["model_selection", "parameter_adjustment", "retraining", "decision_damping"]'::jsonb,
        2,
        0
    )
    RETURNING log_id INTO v_log_id;

    RETURN v_log_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_governance.register_retrospective_decomposition IS
'CEO-DIR-2026-105 Section 2.1: Registers a retrospective decomposition for Non-Eligibility tracking.
Retrospective data cannot be used for prohibited actions until eligibility_date.';


-- ============================================================================
-- SECTION 9: Cohort-Aware Backfill Function
-- ============================================================================

CREATE OR REPLACE FUNCTION fhq_governance.populate_brier_decomposition_retrospective(
    p_start_date DATE DEFAULT NULL,
    p_end_date DATE DEFAULT NULL,
    p_asset_class TEXT DEFAULT NULL
)
RETURNS TABLE (
    inserted_count INTEGER,
    non_eligibility_logged INTEGER,
    cohorts_processed TEXT[]
) AS $$
DECLARE
    v_inserted INTEGER := 0;
    v_non_eligibility INTEGER := 0;
    v_cohorts TEXT[] := ARRAY[]::TEXT[];
    v_record RECORD;
    v_decomposition_id UUID;
BEGIN
    -- Process each decomposition with retrospective flag
    FOR v_record IN
        SELECT
            cmp.*,
            CASE
                WHEN cmp.asset_id LIKE 'BTC%' OR cmp.asset_id LIKE 'ETH%' THEN 'CRYPTO'
                WHEN cmp.asset_id IN ('SPY', 'QQQ', 'IWM') THEN 'EQUITY'
                WHEN cmp.asset_id IN ('GLD', 'TLT', 'UUP') THEN 'MACRO'
                ELSE 'OTHER'
            END AS asset_class_derived
        FROM fhq_governance.compute_brier_decomposition(
            p_start_date := p_start_date,
            p_end_date := p_end_date
        ) cmp
        WHERE (p_asset_class IS NULL OR
               CASE
                   WHEN cmp.asset_id LIKE 'BTC%' OR cmp.asset_id LIKE 'ETH%' THEN 'CRYPTO'
                   WHEN cmp.asset_id IN ('SPY', 'QQQ', 'IWM') THEN 'EQUITY'
                   WHEN cmp.asset_id IN ('GLD', 'TLT', 'UUP') THEN 'MACRO'
                   ELSE 'OTHER'
               END = p_asset_class)
    LOOP
        -- Insert with retrospective flag = TRUE
        INSERT INTO fhq_governance.brier_decomposition (
            asset_id,
            asset_class,
            forecast_type,
            horizon,
            regime,
            period_start,
            period_end,
            sample_size,
            brier_score,
            reliability,
            resolution,
            uncertainty,
            is_retrospective,
            retrospective_computed_at,
            evidence_hash
        ) VALUES (
            v_record.asset_id,
            v_record.asset_class_derived,
            v_record.forecast_type,
            'T+1',  -- Default horizon
            v_record.regime,
            v_record.period_start,
            v_record.period_end,
            v_record.sample_size,
            v_record.brier_score,
            v_record.reliability,
            v_record.resolution,
            v_record.uncertainty,
            TRUE,  -- CRITICAL: Retrospective flag
            NOW(),  -- When analysis was performed
            v_record.evidence_hash || ':RETROSPECTIVE'
        )
        RETURNING decomposition_id INTO v_decomposition_id;

        v_inserted := v_inserted + 1;

        -- Register for non-eligibility tracking
        PERFORM fhq_governance.register_retrospective_decomposition(v_decomposition_id);
        v_non_eligibility := v_non_eligibility + 1;

        -- Track cohorts
        IF NOT v_record.asset_class_derived = ANY(v_cohorts) THEN
            v_cohorts := v_cohorts || v_record.asset_class_derived;
        END IF;
    END LOOP;

    RETURN QUERY SELECT v_inserted, v_non_eligibility, v_cohorts;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fhq_governance.populate_brier_decomposition_retrospective IS
'CEO-DIR-2026-105: Retrospective Brier decomposition backfill with Hindsight Firewall.
All data inserted is marked is_retrospective = TRUE and registered for Non-Eligibility tracking.
Includes cohort binding (asset_class) per Rule 1.';


-- ============================================================================
-- SECTION 10: EPISTEMIC_NULL Handling in Decomposition (Rule 2)
-- ============================================================================

CREATE OR REPLACE VIEW fhq_governance.v_epistemic_null_coverage AS
SELECT
    null_reason AS reason_code,
    COUNT(*) AS total_count,

    -- Rule 2: Included in denominator for coverage calculation
    COUNT(*) AS in_denominator,

    -- Rule 2: Excluded from numerator for accuracy calculation
    0 AS in_numerator_for_accuracy,

    (COUNT(*) * 100.0 / NULLIF((SELECT COUNT(*) FROM fhq_governance.epistemic_null_log), 0))::NUMERIC(5,2) AS pct_of_nulls

FROM fhq_governance.epistemic_null_log
GROUP BY null_reason
ORDER BY total_count DESC;

COMMENT ON VIEW fhq_governance.v_epistemic_null_coverage IS
'CEO-DIR-2026-105 Rule 2: EPISTEMIC_NULL handling.
Predictions with NO_OUTCOME or DATA_QUALITY_FAIL are:
- EXCLUDED from numerator in Reliability calculations (no artificial accuracy)
- INCLUDED in denominator for system coverage rate';


-- ============================================================================
-- SECTION 11: Register Migration
-- ============================================================================

INSERT INTO fhq_governance.governance_actions_log (
    action_type,
    action_target,
    action_target_type,
    initiated_by,
    decision,
    decision_rationale,
    metadata,
    signature,
    agent_id
) VALUES (
    'MIGRATION',
    'CEO-DIR-2026-105',
    'HINDSIGHT_FIREWALL',
    'STIG',
    'APPROVED',
    'Migration 277: Hindsight Firewall - Retrospective epistemic calibration with hindsight boundary',
    jsonb_build_object(
        'migration', '277_hindsight_firewall.sql',
        'directive', 'CEO-DIR-2026-105',
        'ceo_improvements_applied', ARRAY[
            'A: Non-Eligibility Clause (explicit negative rights)',
            'B: VEGA as evidence guardian with cryptographic verification',
            'C: Learning Hypothesis registry (non-executable)',
            'D: Language adjustment (post-hoc disseksjon)'
        ],
        'objects_created', ARRAY[
            'fhq_governance.retrospective_non_eligibility_log',
            'fhq_governance.hindsight_contamination_audit',
            'fhq_governance.learning_hypothesis_registry',
            'fhq_governance.v_calibration_diagnosis_diagnostic',
            'fhq_governance.v_epistemic_null_coverage',
            'fhq_governance.check_hindsight_contamination()',
            'fhq_governance.register_retrospective_decomposition()',
            'fhq_governance.populate_brier_decomposition_retrospective()'
        ],
        'columns_added', ARRAY[
            'brier_decomposition.is_retrospective',
            'brier_decomposition.retrospective_computed_at',
            'brier_decomposition.asset_class',
            'brier_decomposition.horizon'
        ],
        'key_principle', 'Post-hoc disseksjon, ikke obduksjon - systemet lever'
    ),
    'Ed25519:STIG_MIGRATION_277',
    'STIG'
);

COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================
-- Run retrospective backfill:
-- SELECT * FROM fhq_governance.populate_brier_decomposition_retrospective('2025-12-01', '2026-01-19');
--
-- Check hindsight contamination:
-- SELECT * FROM fhq_governance.check_hindsight_contamination();
--
-- View diagnostic data (includes retrospective):
-- SELECT * FROM fhq_governance.v_calibration_diagnosis_diagnostic WHERE is_retrospective = TRUE;
--
-- View SkillDamper inputs (excludes retrospective by default):
-- SELECT * FROM fhq_governance.v_skilldamper_inputs;
--
-- View learning hypothesis:
-- SELECT * FROM fhq_governance.learning_hypothesis_registry;
--
-- View EPISTEMIC_NULL coverage:
-- SELECT * FROM fhq_governance.v_epistemic_null_coverage;
